[workspace]
members = [
    "crates/ast",
    "crates/lexer",
    "crates/parser",
    "crates/resolve",
    "crates/typeck",
    "crates/traits",
    "crates/effects",
    "crates/dbschema",
    "crates/hir",
    "crates/mir",
    "crates/codegen",
]
resolver = "2"

[workspace.dependencies]
logos  = "0.15"
