[workspace]
members = [
    "crates/ast",
    "crates/lexer",
    "crates/parser",
    "crates/resolve",
    "crates/typeck",
    "crates/traits",
    "crates/effects",
    "crates/dbschema",
    "crates/hir",
    "crates/mir",
    "crates/codegen",
    "crates/migrate",
    "crates/cli",
    "crates/lsp",
    "crates/fmt",
    "crates/stdlib",
    "crates/testrunner",
    "crates/llvm",
    "crates/wasm",
    "crates/ffi",
    "crates/ui",
]
resolver = "2"

[workspace.dependencies]
logos  = "0.15"
