use std::fmt::Write as FmtWrite;
use certo_ast::decl::{Decl, TypeBody};
use certo_ast::module::Module;
use certo_hir::{HirModule, HirItem, lower_module};
use certo_mir::lower_fn;
use crate::emit_mir::{emit_fn_with_prefix, c_fn_name};
use crate::ty_to_c::{ty_to_c, ret_ty_to_c, c_ident};
use certo_typeck::Ty;

/// Options controlling C output.
#[derive(Debug, Clone, Default)]
pub struct CodegenOptions {
    /// Include the embedded runtime header inline (default: true).
    pub inline_runtime: bool,
    /// Prefix `pub fn` declarations with `CERTO_EXPORT` for shared library builds.
    pub export_public: bool,
}

/// Emit a complete C translation unit for the given module.
pub fn emit_module(module: &Module, opts: &CodegenOptions) -> String {
    let mut out = String::new();

    // Build set of pub function names for export annotation.
    let pub_fns: std::collections::HashSet<&str> = module.decls.iter()
        .filter_map(|d| if let Decl::Fn(f) = &d.node { Some(f) } else { None })
        .filter(|f| f.is_pub)
        .map(|f| f.name.node.as_str())
        .collect();

    let export = |name: &str| -> &'static str {
        let _ = name; // checked by caller
        if opts.export_public { "CERTO_EXPORT " } else { "" }
    };

    // --- Header ---
    writeln!(out, "/* Generated by Certo compiler — do not edit */").unwrap();
    writeln!(out, "#include <stdint.h>").unwrap();
    writeln!(out, "#include <stdbool.h>").unwrap();
    writeln!(out, "#include <stddef.h>").unwrap();

    if opts.inline_runtime {
        out.push_str(RUNTIME_HEADER);
    } else {
        writeln!(out, "#include \"certo_runtime.h\"").unwrap();
    }

    writeln!(out).unwrap();

    // --- Struct definitions from `type` declarations ---
    for sdecl in &module.decls {
        if let Decl::Type(t) = &sdecl.node {
            match &t.body {
                TypeBody::Record(rec) => {
                    writeln!(out, "typedef struct {{").unwrap();
                    for f in &rec.fields {
                        let cty = ast_ty_to_c_str(&f.ty.node);
                        writeln!(out, "    {} {};", cty, f.name.node).unwrap();
                    }
                    writeln!(out, "}} {};", c_ident(&t.name.node)).unwrap();
                    writeln!(out).unwrap();
                }
                TypeBody::Sum(variants) => {
                    // Emit as tagged union.
                    writeln!(out, "typedef enum {{").unwrap();
                    for v in variants {
                        writeln!(out, "    {}_{},", c_ident(&t.name.node), c_ident(&v.name.node)).unwrap();
                    }
                    writeln!(out, "}} {}_tag_t;", c_ident(&t.name.node)).unwrap();
                    writeln!(out, "typedef struct {{").unwrap();
                    writeln!(out, "    {}_tag_t tag;", c_ident(&t.name.node)).unwrap();
                    writeln!(out, "    union {{").unwrap();
                    for v in variants {
                        if !v.fields.is_empty() {
                            writeln!(out, "        struct {{").unwrap();
                            for (i, f) in v.fields.iter().enumerate() {
                                let fname = f.name.as_ref().map(|n| n.node.clone())
                                    .unwrap_or_else(|| format!("f{}", i));
                                let cty = ast_ty_to_c_str(&f.ty.node);
                                writeln!(out, "            {} {};", cty, fname).unwrap();
                            }
                            writeln!(out, "        }} {};", c_ident(&v.name.node).to_lowercase()).unwrap();
                        }
                    }
                    writeln!(out, "    }};").unwrap();
                    writeln!(out, "}} {};", c_ident(&t.name.node)).unwrap();
                    writeln!(out).unwrap();
                }
                TypeBody::Alias(_) => {} // aliases don't generate structs
            }
        }
    }

    // --- Lower to HIR then MIR and emit functions ---
    let hir = match lower_module(module) {
        Ok(h)  => h,
        Err(e) => {
            writeln!(out, "/* HIR lowering errors: {} */", e.len()).unwrap();
            return out;
        }
    };

    // Forward declarations.
    for item in &hir.items {
        if let HirItem::Fn(f) = item {
            let ret_c = ret_ty_to_c(&f.ret_ty);
            let params: Vec<String> = f.params.iter()
                .map(|p| format!("{} _l{}", ty_to_c(&p.ty), p.local))
                .collect();
            let param_str = if params.is_empty() { "void".into() } else { params.join(", ") };
            let pfx = if pub_fns.contains(f.name.as_str()) { export(&f.name) } else { "" };
            writeln!(out, "{}{} {}({});", pfx, ret_c, c_fn_name(&f.name), param_str).unwrap();
        }
    }
    writeln!(out).unwrap();

    // Function bodies.
    for item in &hir.items {
        match item {
            HirItem::Fn(f) => {
                let pfx = if pub_fns.contains(f.name.as_str()) { export(&f.name) } else { "" };
                let mir = lower_fn(f);
                emit_fn_with_prefix(&mir, pfx, &mut out);
                writeln!(out).unwrap();
            }
            HirItem::Const(c) => {
                // Module-level constants become static C globals.
                let cty = ty_to_c(&c.ty);
                writeln!(out, "static {} {} = {};", cty, c_ident(&c.name),
                    const_expr_to_c(&c.value)).unwrap();
            }
        }
    }

    // If the module has a `main` function, emit a C main() that bootstraps
    // argv and calls it.
    let has_main = module.decls.iter().any(|d| {
        matches!(&d.node, Decl::Fn(f) if f.name.node == "main")
    });
    if has_main {
        writeln!(out, "int main(int argc, const char** argv) {{").unwrap();
        writeln!(out, "    certo_main_init(argc, argv);").unwrap();
        writeln!(out, "    certo_main();").unwrap();
        writeln!(out, "    return 0;").unwrap();
        writeln!(out, "}}").unwrap();
    }

    out
}

// ------------------------------------------------------------------ //
// Helpers
// ------------------------------------------------------------------ //

fn ast_ty_to_c_str(te: &certo_ast::types::TypeExpr) -> String {
    use certo_ast::types::TypeExpr;
    match te {
        TypeExpr::Named { path, .. } => {
            let name = path.segments.last().map(|s| s.node.as_str()).unwrap_or("void");
            match name {
                "Int"     => "int64_t".into(),
                "Float"   => "double".into(),
                "Decimal" => "certo_decimal_t".into(),
                "Bool"    => "bool".into(),
                "Text"    => "certo_text_t".into(),
                "Unit"    => "certo_unit_t".into(),
                "UUID"    => "certo_uuid_t".into(),
                other     => c_ident(other),
            }
        }
        TypeExpr::Option { .. }  => "certo_option_t".into(),
        TypeExpr::Tuple { .. }   => "certo_tuple_t".into(),
        TypeExpr::Fn { .. }      => "certo_fn_t".into(),
        TypeExpr::Record { .. }  => "void*".into(),
        TypeExpr::Ptr { inner, .. } => format!("{}*", ast_ty_to_c_str(&inner.node)),
        TypeExpr::Param { .. }   => "void*".into(),
    }
}

fn const_expr_to_c(expr: &certo_hir::HirExpr) -> String {
    use certo_hir::HirExprKind;
    match &expr.kind {
        HirExprKind::Int(n)     => n.to_string(),
        HirExprKind::Float(f)   => format!("{:.}", f),
        HirExprKind::Bool(b)    => if *b { "true".into() } else { "false".into() },
        HirExprKind::Str(s)     => format!("CERTO_STR(\"{}\")", s),
        HirExprKind::Unit       => "CERTO_UNIT".into(),
        _                       => "/* expr */0".into(),
    }
}

// ------------------------------------------------------------------ //
// Embedded runtime header
// ------------------------------------------------------------------ //

pub const RUNTIME_HEADER: &str = r#"
/* ---- DLL export attribute ---- */
#ifdef _WIN32
#  define CERTO_EXPORT __declspec(dllexport)
#else
#  define CERTO_EXPORT __attribute__((visibility("default")))
#endif

/* ---- Certo runtime types ---- */
typedef int64_t      certo_int_t;
typedef double       certo_float_t;
typedef const char*  certo_text_t;
typedef bool         certo_bool_t;

typedef struct { int _unused; } certo_unit_t;
#define CERTO_UNIT ((certo_unit_t){0})

/* Decimal: stored as scaled integer (cents × 10^scale). */
typedef struct { int64_t value; int8_t scale; } certo_decimal_t;
#define CERTO_DECIMAL(s) certo_decimal_parse(s)
certo_decimal_t certo_decimal_parse(const char* s);

/* Text */
#define CERTO_STR(s) ((certo_text_t)(s))
certo_text_t certo_text_concat(certo_text_t a, certo_text_t b);
int64_t      certo_text_len(certo_text_t t);

/* UUID */
typedef struct { uint8_t bytes[16]; } certo_uuid_t;
#define CERTO_UUID(s) certo_uuid_parse(s)
certo_uuid_t certo_uuid_parse(const char* s);
certo_uuid_t certo_uuid_new(void);

/* Generic option (pointer-sized tag + value) */
typedef struct { bool has_value; void* value; } certo_option_t;
typedef struct { void* value; } certo_tuple_t;
typedef void (*certo_fn_t)(void);
typedef void* certo_error_t;

/* List (dynamic array) — full signatures are in the stdlib C block. */
typedef struct { void** data; int64_t len; int64_t cap; } certo_list_base_t;

/* Arithmetic helpers */
int64_t certo_pow(int64_t base, int64_t exp);
void*   certo_coalesce(void* opt, void* fallback);

/* Panic */
__attribute__((noreturn)) void certo_panic(certo_text_t msg);
#define certo_unreachable() certo_panic("unreachable")
#define certo_todo()        certo_panic("not yet implemented")

/* stdin */
certo_text_t certo_read_line(void);
certo_text_t certo_read_all(void);

/* argv — call certo_main_init(argc, argv) at the top of main() */
void    certo_main_init(int argc, const char** argv);
int64_t certo_arg_count(void);
certo_text_t certo_arg(int64_t i);

/* DB transaction stub */
void* __db_transaction(certo_fn_t thunk);

/* Try/unwrap (Result<T,E> → T, or propagate) */
void* __try_unwrap(void* result);

/* Record update */
void* __record_update(void* base, void* updates);
/* ---- end Certo runtime ---- */
"#;
