use std::fmt::Write as FmtWrite;
use certo_ast::decl::{Decl, TypeBody, StateMachineDecl};
use certo_ast::module::Module;
use certo_hir::{HirFn, HirItem, lower_module};
use certo_mir::lower_fn;
use crate::emit_mir::{emit_fn_with_prefix, c_fn_name, collect_spawn_sites, emit_spawn_support, set_extern_names, LineMap};
use crate::ty_to_c::{ty_to_c, ret_ty_to_c, c_ident};

/// Options controlling C output.
#[derive(Debug, Clone, Default)]
pub struct CodegenOptions {
    /// Include the embedded runtime header inline (default: true).
    pub inline_runtime: bool,
    /// Prefix `pub fn` declarations with `CERTO_EXPORT` for shared library builds.
    pub export_public: bool,
    /// `Some((filename, source))` opts into emitting `#line` directives that
    /// map generated C back to the original `.cto` file/line, so coverage
    /// tools (`llvm-cov`) attribute results to the user's own source instead
    /// of meaningless generated-C line numbers — BACKLOG item 126. `None`
    /// (the default) for every normal `certo build`/`run`/`test` path;
    /// only `certo test --coverage`'s own C generation opts in, so ordinary
    /// compile-error messages keep pointing at the generated C as before.
    pub line_directives: Option<(String, String)>,
}

/// Emit a complete C translation unit for the given module.
pub fn emit_module(module: &Module, opts: &CodegenOptions) -> String {
    let mut out = String::new();
    let line_map: Option<LineMap> = opts.line_directives.as_ref()
        .map(|(filename, source)| LineMap::new(filename, source));

    // BACKLOG item 242 — must run before any codegen call below, since
    // `c_fn_name` consults this registry on every call.
    set_extern_names(module.decls.iter().filter_map(|sdecl| match &sdecl.node {
        Decl::Fn(f) if f.is_extern => Some(f.name.node.clone()),
        _ => None,
    }).collect());

    // All-nullary enums are represented as plain int enums (not structs). The
    // function emitters need to know which, so `match`'s `.tag` read on such a
    // value compiles to the value itself. Populated during type emission below.
    let mut nullary_enums: std::collections::HashSet<String> = std::collections::HashSet::new();

    // BACKLOG item 201 — type names that got a real, generated
    // `certo_eq_<Name>` structural-equality function (see `build_type_shapes`/
    // `ty_is_comparable` below); `emit_binop`'s `BinOp::Eq`/`NotEq` consult
    // this to call it instead of emitting an invalid bare C `==` on a struct.
    let mut eq_types: std::collections::HashSet<String> = std::collections::HashSet::new();

    // A nullary variant's own name → its parent sum type's name, for every
    // variant of every sum type (not just mixed ones) — BACKLOG item 201.
    // A bare nullary-variant *constant* reference (`Origin == Origin`) is
    // `Operand::Global`, which has no `MirLocalDecl` to recover a type
    // from; `emit_binop` consults this to find the parent type (and from
    // there, whether it's in `eq_types`) when that happens.
    let mut variant_parent: std::collections::HashMap<String, String> = std::collections::HashMap::new();

    // Build set of pub function names for export annotation.
    let pub_fns: std::collections::HashSet<&str> = module.decls.iter()
        .filter_map(|d| if let Decl::Fn(f) = &d.node { Some(f) } else { None })
        .filter(|f| f.is_pub)
        .map(|f| f.name.node.as_str())
        .collect();

    // `@export("name")` — maps a pub fn's Certo name to the custom C symbol it
    // should additionally be exported under (parser guarantees export_name
    // implies is_pub). The internal function keeps its usual mangled name
    // (`certo_<name>`) for in-module calls; a thin exported wrapper is emitted
    // separately (see `export_wrappers` below) so callers inside the module
    // aren't affected by the external symbol name.
    let export_names: std::collections::HashMap<&str, &str> = module.decls.iter()
        .filter_map(|d| if let Decl::Fn(f) = &d.node { Some(f) } else { None })
        .filter_map(|f| f.export_name.as_deref().map(|n| (f.name.node.as_str(), n)))
        .collect();

    let export = |name: &str| -> &'static str {
        let _ = name; // checked by caller
        if opts.export_public { "CERTO_EXPORT " } else { "" }
    };

    // --- Header ---
    writeln!(out, "/* Generated by Certo compiler — do not edit */").unwrap();
    writeln!(out, "#include <stdint.h>").unwrap();
    writeln!(out, "#include <stdbool.h>").unwrap();
    writeln!(out, "#include <stddef.h>").unwrap();

    if opts.inline_runtime {
        out.push_str(RUNTIME_HEADER);
    } else {
        writeln!(out, "#include \"certo_runtime.h\"").unwrap();
    }

    writeln!(out).unwrap();

    // BACKLOG item 201 — which types can get a real, generated
    // `certo_eq_<Name>` structural-equality function, computed once up
    // front so field comparability can look *forward* too, not just
    // backward through already-emitted types.
    let type_shapes = build_type_shapes(module);

    // --- Struct definitions from `type` declarations ---
    for sdecl in &module.decls {
        if let Decl::Type(t) = &sdecl.node {
            let type_params: Vec<String> = t.type_params.iter().map(|tp| tp.name.node.clone()).collect();
            match &t.body {
                TypeBody::Record(rec) => {
                    writeln!(out, "typedef struct {{").unwrap();
                    for f in &rec.fields {
                        let cty = field_c_ty(&f.ty.node, &type_params, None);
                        writeln!(out, "    {} {};", cty, f.name.node).unwrap();
                    }
                    writeln!(out, "}} {};", c_ident(&t.name.node)).unwrap();
                    writeln!(out).unwrap();

                    // BACKLOG item 201 — a plain-value struct's `==`/`!=`
                    // don't compile in C at all (`invalid operands to
                    // binary expression`), directly contradicting the
                    // spec's own §8.4 "equality is structural" claim.
                    // Only emitted when every field (recursively) is one
                    // this function knows how to compare correctly —
                    // generic type params, and List/Option/Map/Tuple/Fn-
                    // typed fields, are deliberately excluded (a `void*`
                    // slot has no single correct comparison without the
                    // same generic-erasure machinery item 200's own design
                    // sketch describes) — `==` on such a type is left
                    // exactly as broken as before, a clean C compile
                    // error, not a silently wrong comparison.
                    if type_params.is_empty() && rec.fields.iter().all(|f| !f.optional && ty_is_comparable(&f.ty.node, &type_shapes)) {
                        let tname = c_ident(&t.name.node);
                        writeln!(out, "static inline bool certo_eq_{tname}({tname} a, {tname} b) {{").unwrap();
                        let parts: Vec<String> = rec.fields.iter()
                            .map(|f| emit_field_cmp(&format!("a.{}", f.name.node), &format!("b.{}", f.name.node), &f.ty.node, &type_shapes))
                            .collect();
                        let body = if parts.is_empty() { "true".to_string() } else { parts.join(" && ") };
                        writeln!(out, "    return {body};").unwrap();
                        writeln!(out, "}}").unwrap();
                        writeln!(out).unwrap();
                        eq_types.insert(t.name.node.clone());
                    }

                    // BACKLOG item 262 — positional record construction
                    // (spec §8.4, e.g. `Money(d"10.00", USD)`). Mirrors a
                    // sum-type variant-with-fields constructor's own
                    // codegen exactly (see the `TypeBody::Sum` arm below):
                    // an ordinary real C function, named to match how HIR/
                    // MIR reference the record type's own bare name as a
                    // call target (`c_fn_name`), taking every declared
                    // field positionally in declaration order. `computed`
                    // fields are never parameters (they have no backing
                    // storage to initialize); this matches typeck/HIR's own
                    // exclusion of them from the constructor's registered
                    // arity.
                    let tname = c_ident(&t.name.node);
                    let cname = crate::emit_mir::c_fn_name(&t.name.node);
                    let params: Vec<String> = rec.fields.iter().map(|f| {
                        let cty = field_c_ty(&f.ty.node, &type_params, None);
                        format!("{cty} {}", f.name.node)
                    }).collect();
                    let inits: Vec<String> = rec.fields.iter()
                        .map(|f| format!(".{0} = {0}", f.name.node))
                        .collect();
                    writeln!(out, "static inline {tname} {cname}({}) {{", params.join(", ")).unwrap();
                    writeln!(out, "    {tname} _v = {{ {} }};", inits.join(", ")).unwrap();
                    writeln!(out, "    return _v;").unwrap();
                    writeln!(out, "}}").unwrap();
                    writeln!(out).unwrap();
                }
                TypeBody::Sum(variants) => {
                    let tname = c_ident(&t.name.node);
                    let has_payload = variants.iter().any(|v| !v.fields.is_empty());
                    for v in variants {
                        if v.fields.is_empty() {
                            variant_parent.insert(v.name.node.clone(), t.name.node.clone());
                        }
                    }
                    if has_payload {
                        // Tagged union: a tag enum plus a struct with a payload union.
                        writeln!(out, "typedef enum {{").unwrap();
                        for v in variants {
                            writeln!(out, "    {}_{},", tname, c_ident(&v.name.node)).unwrap();
                        }
                        writeln!(out, "}} {}_tag_t;", tname).unwrap();
                        // BACKLOG item 277 — a named struct tag (not just the
                        // eventual typedef alias), so a *direct* self-
                        // referential field further down (`struct {tname}*`)
                        // can reference this same struct from inside its own
                        // body — the typedef name `{tname}` itself isn't a
                        // valid type until this whole `typedef ... ;`
                        // completes. Harmless to add unconditionally: a
                        // non-recursive payload type never references the
                        // tag at all.
                        writeln!(out, "typedef struct {} {{", tname).unwrap();
                        writeln!(out, "    {}_tag_t tag;", tname).unwrap();
                        writeln!(out, "    union {{").unwrap();
                        for v in variants {
                            if !v.fields.is_empty() {
                                writeln!(out, "        struct {{").unwrap();
                                for (i, f) in v.fields.iter().enumerate() {
                                    let fname = f.name.as_ref().map(|n| n.node.clone())
                                        .unwrap_or_else(|| format!("f{}", i));
                                    let cty = field_c_ty(&f.ty.node, &type_params, Some(t.name.node.as_str()));
                                    writeln!(out, "            {} {};", cty, fname).unwrap();
                                }
                                writeln!(out, "        }} {};", c_ident(&v.name.node).to_lowercase()).unwrap();
                            }
                        }
                        writeln!(out, "    }};").unwrap();
                        writeln!(out, "}} {};", tname).unwrap();

                        // BACKLOG item 201 — same structural-equality
                        // treatment as records, just tag-then-payload:
                        // two values only compare equal when the active
                        // variant matches *and* that variant's own fields
                        // (recursively) do. A variant with no fields needs
                        // nothing further once the tag already matched.
                        let comparable = type_params.is_empty()
                            && variants.iter().all(|v| v.fields.iter().all(|f| ty_is_comparable(&f.ty.node, &type_shapes)));
                        if comparable {
                            writeln!(out, "static inline bool certo_eq_{tname}({tname} a, {tname} b) {{").unwrap();
                            writeln!(out, "    if (a.tag != b.tag) return false;").unwrap();
                            writeln!(out, "    switch (a.tag) {{").unwrap();
                            for v in variants {
                                let member = c_ident(&v.name.node).to_lowercase();
                                let cmp = if v.fields.is_empty() {
                                    "true".to_string()
                                } else {
                                    v.fields.iter().enumerate().map(|(i, f)| {
                                        let fname = f.name.as_ref().map(|n| n.node.clone()).unwrap_or_else(|| format!("f{i}"));
                                        emit_field_cmp(&format!("a.{member}.{fname}"), &format!("b.{member}.{fname}"), &f.ty.node, &type_shapes)
                                    }).collect::<Vec<_>>().join(" && ")
                                };
                                writeln!(out, "        case {tname}_{}: return {cmp};", c_ident(&v.name.node)).unwrap();
                            }
                            writeln!(out, "        default: return true;").unwrap();
                            writeln!(out, "    }}").unwrap();
                            writeln!(out, "}}").unwrap();
                            writeln!(out).unwrap();
                            eq_types.insert(t.name.node.clone());
                        }
                    } else {
                        // All-nullary: a plain integer enum, so values are pointer-sized
                        // and can flow through Result / List / tuple slots unchanged.
                        writeln!(out, "typedef enum {{").unwrap();
                        for v in variants {
                            writeln!(out, "    {}_{},", tname, c_ident(&v.name.node)).unwrap();
                        }
                        writeln!(out, "}} {};", tname).unwrap();
                        nullary_enums.insert(t.name.node.clone());
                    }
                    // Emit unit-variant constants.
                    // Use snake_case (via c_fn_name logic) to match how the codegen references globals.
                    for v in variants {
                        if v.fields.is_empty() {
                            let vname = c_ident(&v.name.node);
                            let cname = crate::emit_mir::c_fn_name(&v.name.node); // e.g. certo_red
                            if has_payload {
                                // Struct representation: initialise the tag field.
                                writeln!(out, "static const {tname} {cname} = {{ .tag = {tname}_{vname} }};").unwrap();
                            } else {
                                // Integer representation: the constant is the tag value.
                                writeln!(out, "static const {tname} {cname} = {tname}_{vname};").unwrap();
                            }
                        } else {
                            // Emit constructor function. The function name must match how
                            // call sites reference it (`c_fn_name`, snake_case), while the
                            // tag and union member keep the `c_ident` form.
                            let vname = c_ident(&v.name.node);
                            let cname = crate::emit_mir::c_fn_name(&v.name.node);
                            let params: Vec<String> = v.fields.iter().enumerate().map(|(i, f)| {
                                let fname = f.name.as_ref().map(|n| n.node.clone()).unwrap_or_else(|| format!("f{i}"));
                                let cty = field_c_ty(&f.ty.node, &type_params, Some(t.name.node.as_str()));
                                format!("{cty} {fname}")
                            }).collect();
                            let inits: Vec<String> = v.fields.iter().enumerate().map(|(i, f)| {
                                let fname = f.name.as_ref().map(|n| n.node.clone()).unwrap_or_else(|| format!("f{i}"));
                                format!(".{fname} = {fname}")
                            }).collect();
                            writeln!(out, "static inline {tname} {cname}({}) {{", params.join(", ")).unwrap();
                            writeln!(out, "    {tname} _v = {{ .tag = {tname}_{vname}, .{} = {{ {} }} }};",
                                vname.to_lowercase(), inits.join(", ")).unwrap();
                            writeln!(out, "    return _v;").unwrap();
                            writeln!(out, "}}").unwrap();
                        }
                    }
                    writeln!(out).unwrap();
                }
                TypeBody::Alias(_) => {} // aliases don't generate structs
            }
        }
    }

    // --- State machine type and function definitions ---
    for sdecl in &module.decls {
        if let Decl::StateMachine(sm) = &sdecl.node {
            emit_statemachine(sm, &mut out);
        }
    }

    // --- Lower to HIR then MIR and emit functions ---
    let hir = match lower_module(module) {
        Ok(h)  => h,
        Err(e) => {
            writeln!(out, "/* HIR lowering errors: {} */", e.len()).unwrap();
            return out;
        }
    };

    // Lower all functions to MIR once so the actual return types are known.
    // HirFn.ret_ty is Ty::Error (a placeholder) — the MIR return slot (local 0)
    // holds the real type after lower_fn() infers it from the function body.
    let mut lifted_fns: Vec<certo_mir::MirFn> = Vec::new();
    let fn_mirs: Vec<(certo_mir::MirFn, &str)> = hir.items.iter()
        .filter_map(|item| if let HirItem::Fn(f) = item {
            let (mir, lifted) = lower_fn(f, &hir.record_field_types, &hir.variant_field_types, &hir.fn_param_tys, &hir.fn_ret_tys, &hir.variant_to_type);
            lifted_fns.extend(lifted);
            Some((mir, f.name.as_str()))
        } else {
            None
        })
        .collect();

    // A module-level `val name = <expr>` whose initializer isn't a simple
    // compile-time-constant literal previously compiled to a bare
    // `static T name = /* expr */0;` — `const_expr_to_c`'s fallback for
    // anything it can't render as a literal C expression — silently
    // discarding the real initializer entirely and leaving `name` at a
    // placeholder zero/NULL forever. Confirmed with a direct repro
    // (`val conn = dbConnect(...)` always NULL, `dbError` always
    // "connection failed") while building BACKLOG item 154, then found to
    // be fully general — `fn five(): Int = 5` / `val x = five()` prints `0`,
    // not `5` — not specific to DB or the REPL at all (BACKLOG item 168).
    //
    // Fixed by reusing the existing function-lowering pipeline instead of
    // trying to render an arbitrary expression as a single C expression (the
    // dead-end `const_expr_to_c`/`simple_expr_to_c` were already attempting
    // and abandoning): each such `val` gets a synthesized zero-arg
    // `__certo_init_<name>` function whose body *is* the real initializer,
    // lowered and emitted exactly like an ordinary function (so it gets
    // real MIR, real boxing/unboxing, real multi-statement bodies — nothing
    // new to prove correct). The global itself is declared uninitialized
    // (`static T name;`, zero-init by plain C semantics) and assigned from
    // the init function's return value in the generated bootstrap, right
    // after `certo_main_init(...)` and before the user's own `main()` body
    // runs — see the `has_main` block below. Literal initializers are left
    // completely untouched (still real, valid C constant expressions,
    // zero behavior change, zero risk).
    let is_simple_const_literal = |value: &certo_hir::HirExpr| {
        matches!(&value.kind,
            certo_hir::HirExprKind::Int(_) | certo_hir::HirExprKind::Float(_) |
            certo_hir::HirExprKind::Bool(_) | certo_hir::HirExprKind::Str(_) |
            certo_hir::HirExprKind::Unit)
    };
    let mut const_init_fns: Vec<(String, certo_mir::MirFn)> = Vec::new();
    for item in &hir.items {
        if let HirItem::Const(c) = item {
            if !is_simple_const_literal(&c.value) {
                let init_fn = HirFn {
                    id: 0,
                    name: format!("__certo_init_{}", c.name),
                    params: vec![],
                    ret_ty: certo_typeck::Ty::Error,
                    body: Some(c.value.clone()),
                    span: c.span,
                };
                let (mir, lifted) = lower_fn(&init_fn, &hir.record_field_types, &hir.variant_field_types, &hir.fn_param_tys, &hir.fn_ret_tys, &hir.variant_to_type);
                lifted_fns.extend(lifted);
                const_init_fns.push((c.name.clone(), mir));
            }
        }
    }

    // Forward declarations — use MIR local[0].ty for the return type.
    // Also collect signatures for any `@export("name")` wrapper (emitted
    // below, after all forward declarations exist for it to call into).
    let mut export_wrappers: Vec<String> = Vec::new();
    for (mir, _) in &fn_mirs {
        let ret_ty = mir.locals.first().map(|l| &l.ty).unwrap_or(&certo_typeck::Ty::Unit);
        let ret_c  = ret_ty_to_c(ret_ty);
        let arg_tys: Vec<(String, u32)> = mir.locals.iter().skip(1).take(mir.param_count)
            .map(|l| (ty_to_c(&l.ty), l.id))
            .collect();
        let params: Vec<String> = arg_tys.iter().map(|(ty, id)| format!("{} _l{}", ty, id)).collect();
        let param_str = if params.is_empty() { "void".into() } else { params.join(", ") };
        let pfx = if pub_fns.contains(mir.name.as_str()) { export(&mir.name) } else { "" };
        writeln!(out, "{}{} {}({});", pfx, ret_c, c_fn_name(&mir.name), param_str).unwrap();
        if let Some(export_name) = export_names.get(mir.name.as_str()) {
            let args: Vec<String> = arg_tys.iter().map(|(_, id)| format!("_l{}", id)).collect();
            export_wrappers.push(format!("{}{} {}({}) {{ return {}({}); }}",
                export(export_name), ret_c, c_ident(export_name), param_str, c_fn_name(&mir.name), args.join(", ")));
        }
    }
    // Emit the exported wrappers: a thin function under the custom C symbol
    // name that just forwards to the internal `certo_<name>` definition.
    for wrapper in &export_wrappers {
        writeln!(out, "{}", wrapper).unwrap();
    }
    // Forward-declare `extern "C"` FFI functions. They have no Certo body; the
    // definition is provided by a library linked via `--link`. Emitting an
    // explicit prototype (rather than relying on an implicit declaration, which
    // C assumes returns `int`) is essential so the 64-bit Int ABI is correct.
    for sdecl in &module.decls {
        if let Decl::Fn(f) = &sdecl.node {
            if !f.is_extern { continue; }
            let ret_c = match &f.ret_ty {
                Some(ann) => ast_ty_to_c_str(&ann.node),
                None      => "certo_unit_t".into(),
            };
            let params: Vec<String> = f.params.iter()
                .map(|p| ast_ty_to_c_str(&p.ty.node))
                .collect();
            let param_str = if params.is_empty() { "void".into() } else { params.join(", ") };
            writeln!(out, "{} {}({});", ret_c, c_fn_name(&f.name.node), param_str).unwrap();
        }
    }
    // Forward-declare lifted lambdas.
    for mir in &lifted_fns {
        let ret_ty = mir.locals.first().map(|l| &l.ty).unwrap_or(&certo_typeck::Ty::Unit);
        let ret_c  = ret_ty_to_c(ret_ty);
        let params: Vec<String> = mir.locals.iter().skip(1).take(mir.param_count)
            .map(|l| format!("{} _l{}", ty_to_c(&l.ty), l.id))
            .collect();
        let param_str = if params.is_empty() { "void".into() } else { params.join(", ") };
        writeln!(out, "static {} {}({});", ret_c, c_fn_name(&mir.name), param_str).unwrap();
    }
    // Forward-declare the synthesized `__certo_init_<name>` functions for any
    // module-level `val` with a non-literal initializer (BACKLOG item 168).
    for (_, mir) in &const_init_fns {
        let ret_ty = mir.locals.first().map(|l| &l.ty).unwrap_or(&certo_typeck::Ty::Unit);
        let ret_c  = ret_ty_to_c(ret_ty);
        writeln!(out, "static {} {}(void);", ret_c, c_fn_name(&mir.name)).unwrap();
    }
    writeln!(out).unwrap();

    // Concurrency support: per-spawn-call-site context structs + thread workers.
    // Emitted after all forward declarations so workers can call any function,
    // and before the function bodies that reference them.
    {
        let mut emitted_joins: std::collections::HashSet<String> = std::collections::HashSet::new();
        let mut any = false;
        let mut support = String::new();
        for (mir, _) in &fn_mirs {
            let sites = collect_spawn_sites(mir);
            if !sites.is_empty() { any = true; }
            emit_spawn_support(&sites, &mut emitted_joins, &mut support);
        }
        for mir in &lifted_fns {
            let sites = collect_spawn_sites(mir);
            if !sites.is_empty() { any = true; }
            emit_spawn_support(&sites, &mut emitted_joins, &mut support);
        }
        if any {
            out.push_str("/* ---- spawn workers ---- */\n");
            out.push_str(&support);
            writeln!(out).unwrap();
        }
    }

    // Emit lifted lambda bodies before user functions.
    for mir in &lifted_fns {
        emit_fn_with_prefix(mir, "static ", &nullary_enums, &eq_types, &variant_parent, line_map.as_ref(), &mut out);
        writeln!(out).unwrap();
    }
    // `__certo_init_<name>` function *bodies* are deliberately NOT emitted
    // here alongside lifted lambdas (only forward-declared above) — unlike a
    // lifted lambda, an init function's body can reference *other*
    // module-level globals (`val twenty = double(ten)`), which — like any
    // top-level Certo declaration — only exist in the generated C once their
    // own `static T name;` line has been emitted. Emitting every init body
    // in one early batch, before any global's declaration, produced a real,
    // confirmed "undeclared identifier" compile error for exactly that case.
    // Each init function's body is instead emitted below, in the interleaved
    // Const/Fn loop, at the same point as its own const's declaration — the
    // same source-order-dependent rule ordinary top-level Certo code already
    // has (a `val` must be declared before something later in the file uses
    // it), not a new limitation.

    // Emit function bodies from cached MIR.
    // Interleave any non-Fn HIR items (Const) at the right position.
    let const_init_fn_by_name: std::collections::HashMap<&str, &certo_mir::MirFn> =
        const_init_fns.iter().map(|(name, mir)| (name.as_str(), mir)).collect();
    {
        let mut mir_iter = fn_mirs.into_iter();
        for item in &hir.items {
            match item {
            HirItem::Fn(_) => {
                if let Some((mir, name)) = mir_iter.next() {
                    let pfx = if pub_fns.contains(name) { export(name) } else { "" };
                    emit_fn_with_prefix(&mir, pfx, &nullary_enums, &eq_types, &variant_parent, line_map.as_ref(), &mut out);
                    writeln!(out).unwrap();
                }
            }
            HirItem::Const(c) => {
                // Module-level constants become static C globals.
                if let Some(init_mir) = const_init_fn_by_name.get(c.name.as_str()) {
                    // Non-literal initializer (BACKLOG item 168) — declared
                    // uninitialized (zero-init by plain C semantics) and
                    // really assigned from `__certo_init_<name>()` in the
                    // bootstrap below, before `main()`'s own body runs. Use
                    // the init function's own inferred return type — more
                    // accurate than `const_expr_ty`'s crude non-literal
                    // fallback (`void*` for anything it doesn't recognize).
                    let cty = init_mir.locals.first().map(|l| ty_to_c(&l.ty)).unwrap_or_else(|| "void*".into());
                    writeln!(out, "static {} {};", cty, c_fn_name(&c.name)).unwrap();
                    // The init function's own body, emitted here (not in one
                    // early batch) so any *other* global it references has
                    // already been declared, per the doc comment above.
                    emit_fn_with_prefix(*init_mir, "static ", &nullary_enums, &eq_types, &variant_parent, line_map.as_ref(), &mut out);
                    writeln!(out).unwrap();
                } else {
                    // Use the expression type when the declared type is unknown (Ty::Error).
                    let cty = if matches!(c.ty, certo_typeck::Ty::Error) {
                        const_expr_ty(&c.value)
                    } else {
                        ty_to_c(&c.ty)
                    };
                    writeln!(out, "static {} {} = {};", cty, c_fn_name(&c.name),
                        const_expr_to_c(&c.value)).unwrap();
                }
            }
            }
        }
    }

    // If the module has a `main` function, emit a C main() that bootstraps
    // argv and calls it.
    let has_main = module.decls.iter().any(|d| {
        matches!(&d.node, Decl::Fn(f) if f.name.node == "main")
    });
    if has_main {
        // Real initialization for any module-level `val` with a non-literal
        // initializer (BACKLOG item 168) — run once, before the user's own
        // `main()` body, so every later reference sees the real computed
        // value rather than the zero/NULL the global starts as.
        let mut global_inits = String::new();
        for (name, mir) in &const_init_fns {
            writeln!(global_inits, "    {} = {}();", c_fn_name(name), c_fn_name(&mir.name)).unwrap();
        }
        // On Windows emit a wmain entry point so the CRT passes wchar_t** argv,
        // which is derived directly from CommandLineToArgvW — immune to shells
        // (Git Bash, PowerShell, cmd) stripping or mangling quoted arguments.
        writeln!(out, "#ifdef _WIN32").unwrap();
        writeln!(out, "int wmain(int argc, wchar_t** argv) {{").unwrap();
        writeln!(out, "    char** u8 = (char**)malloc((size_t)argc * sizeof(char*));").unwrap();
        writeln!(out, "    for (int i = 0; i < argc; i++) {{").unwrap();
        writeln!(out, "        int n = WideCharToMultiByte(CP_UTF8,0,argv[i],-1,NULL,0,NULL,NULL);").unwrap();
        writeln!(out, "        u8[i] = (char*)malloc((size_t)n);").unwrap();
        writeln!(out, "        WideCharToMultiByte(CP_UTF8,0,argv[i],-1,u8[i],n,NULL,NULL);").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "    certo_main_init(argc, (const char**)u8);").unwrap();
        write!(out, "{}", global_inits).unwrap();
        writeln!(out, "    certo_main();").unwrap();
        writeln!(out, "    return 0;").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out, "int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow) {{").unwrap();
        writeln!(out, "    int argc = 0;").unwrap();
        writeln!(out, "    wchar_t** argv = CommandLineToArgvW(GetCommandLineW(), &argc);").unwrap();
        writeln!(out, "    return wmain(argc, argv);").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out, "#else").unwrap();
        writeln!(out, "int main(int argc, const char** argv) {{").unwrap();
        writeln!(out, "    certo_main_init(argc, argv);").unwrap();
        write!(out, "{}", global_inits).unwrap();
        writeln!(out, "    certo_main();").unwrap();
        writeln!(out, "    return 0;").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out, "#endif").unwrap();
    }

    out
}

// ------------------------------------------------------------------ //
// State machine emission
// ------------------------------------------------------------------ //

/// Emit C types and functions for a `statemachine` declaration.
fn emit_statemachine(sm: &StateMachineDecl, out: &mut String) {
    use std::fmt::Write as FmtWrite;
    let mname = c_ident(&sm.name.node);

    // 1. State enum.
    writeln!(out, "typedef enum {{").unwrap();
    for (i, state) in sm.states.iter().enumerate() {
        let comma = if i + 1 < sm.states.len() { "," } else { "" };
        writeln!(out, "    {}_{}{}",  mname, c_ident(&state.node), comma).unwrap();
    }
    writeln!(out, "}} {}State;", mname).unwrap();
    writeln!(out).unwrap();

    // 2. Machine struct — always has `state` field; extra fields from transition params.
    // Collect unique (name, C-type) pairs across all transitions.
    let mut fields: Vec<(String, String)> = Vec::new();
    for t in &sm.transitions {
        for p in &t.params {
            let pname = p.name.node.clone();
            if !fields.iter().any(|(n, _)| n == &pname) {
                let cty = ast_ty_to_c_str(&p.ty.node);
                fields.push((pname, cty));
            }
        }
    }
    writeln!(out, "typedef struct {{").unwrap();
    writeln!(out, "    {}State state;", mname).unwrap();
    for (fname, cty) in &fields {
        writeln!(out, "    {} {};", cty, fname).unwrap();
    }
    writeln!(out, "}} {};", mname).unwrap();
    writeln!(out).unwrap();

    // 3. Constructor: MachineName_new() — initial state is the first state.
    let init_state = sm.states.first().map(|s| s.node.as_str()).unwrap_or("_Unknown");
    let ctor_c = c_fn_name(&format!("{}_new", sm.name.node));
    writeln!(out, "{} {}(void) {{", mname, ctor_c).unwrap();
    writeln!(out, "    {} _m = {{0}};", mname).unwrap();
    writeln!(out, "    _m.state = {}_{};", mname, c_ident(init_state)).unwrap();
    writeln!(out, "    return _m;").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // 4. Transition functions.
    for t in &sm.transitions {
        let from   = c_ident(&t.from.node);
        let to     = c_ident(&t.to.node);
        let fn_c   = c_fn_name(&format!("{}_{}", sm.name.node, t.event.node));

        // Build param list: machine first, then event params.
        let mut param_parts = vec![format!("{} _self", mname)];
        for p in &t.params {
            let cty = ast_ty_to_c_str(&p.ty.node);
            param_parts.push(format!("{} _{}", cty, p.name.node));
        }
        let param_str = param_parts.join(", ");

        writeln!(out, "{} {}({}) {{", mname, fn_c, param_str).unwrap();
        // Guard: must be in `from` state.
        writeln!(out, "    if (_self.state != {}_{}) {{", mname, from).unwrap();
        writeln!(out, "        certo_panic(CERTO_STR(\"invalid transition {}: expected state {}\"));",
            t.event.node, t.from.node).unwrap();
        writeln!(out, "    }}").unwrap();
        // Assign transition params into the struct.
        for p in &t.params {
            writeln!(out, "    _self.{} = _{};", p.name.node, p.name.node).unwrap();
        }
        // Check invariants on the `from` state before leaving (future: emit body).
        for inv in sm.invariants.iter().filter(|i| i.state.node == t.from.node) {
            let _ = inv;
            writeln!(out, "    /* invariant check for {} */", t.from.node).unwrap();
        }
        // Set new state.
        writeln!(out, "    _self.state = {}_{};", mname, to).unwrap();
        // Inline on_enter hook if one exists for the target state.
        for hook in sm.on_enter.iter().filter(|h| h.state.node == t.to.node) {
            if let Some(c) = simple_expr_to_c(&hook.body.node) {
                writeln!(out, "    {};", c).unwrap();
            } else {
                writeln!(out, "    /* on_enter {}: complex expression */", t.to.node).unwrap();
            }
        }
        writeln!(out, "    return _self;").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    // 5. State predicates: MachineName_isState(m) -> bool
    for state in &sm.states {
        let sname    = c_ident(&state.node);
        let pred_c   = c_fn_name(&format!("{}_is{}", sm.name.node, state.node));
        writeln!(out, "bool {}({} _self) {{", pred_c, mname).unwrap();
        writeln!(out, "    return _self.state == {}_{};", mname, sname).unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    // 6. State accessor: MachineName_state(m) -> MachineName_state (as int)
    let state_acc_c = c_fn_name(&format!("{}_state", sm.name.node));
    writeln!(out, "{}State {}({} _self) {{", mname, state_acc_c, mname).unwrap();
    writeln!(out, "    return _self.state;").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

}

// ------------------------------------------------------------------ //
// Structural equality (`==`/`!=` on records/enums) — BACKLOG item 201
// ------------------------------------------------------------------ //

/// The shape of a user-declared `type` needed to decide whether its own
/// values can be compared with `==`, and if so, how.
enum TypeShape<'a> {
    Record(&'a [certo_ast::decl::RecordFieldDef]),
    NullaryEnum,
    PayloadEnum(&'a [certo_ast::decl::SumVariant]),
}

/// One pass over every `type` declaration, before any C is emitted, so
/// `ty_is_comparable` can look *forward* to a type declared later in the
/// file too, not just backward through whatever's already been emitted.
/// `ty_is_comparable` itself (via `ty_is_comparable_inner`) is the one that
/// guards against a cyclic type — BACKLOG item 259 found a self-referential
/// *sum* type (`Node(left: Tree, right: Tree)`, a perfectly valid recursive
/// data structure) is not the "already an infinite-size C struct, so it's
/// someone else's problem" case this comment used to assume: a payload
/// field needing heap-boxing is already stored as a pointer in C, so the
/// struct itself is finite and compiles fine — it was `ty_is_comparable`'s
/// own unguarded structural recursion through the *declared* field types
/// (not the C memory layout) that looped forever, a real Rust stack
/// overflow in the compiler itself, confirmed live via `certo build` on
/// the spec's own `Tree` example.
fn build_type_shapes(module: &Module) -> std::collections::HashMap<String, TypeShape<'_>> {
    let mut shapes = std::collections::HashMap::new();
    for sdecl in &module.decls {
        if let Decl::Type(t) = &sdecl.node {
            if !t.type_params.is_empty() { continue; } // generic — not comparable, see ty_is_comparable
            match &t.body {
                TypeBody::Record(rec) => { shapes.insert(t.name.node.clone(), TypeShape::Record(&rec.fields)); }
                TypeBody::Sum(variants) => {
                    let has_payload = variants.iter().any(|v| !v.fields.is_empty());
                    shapes.insert(t.name.node.clone(),
                        if has_payload { TypeShape::PayloadEnum(variants) } else { TypeShape::NullaryEnum });
                }
                TypeBody::Alias(_) => {}
            }
        }
    }
    shapes
}

/// Can a value of this type be compared with `==`/`!=` at all, given this
/// codebase's current C representation? Scalars/Text/Decimal/UUID always
/// can; a user record/enum can when every one of its own fields
/// (recursively) can. Deliberately conservative — an `optional` field, a
/// generic type param slot (erased to `void*`), and every
/// List/Option/Map/Tuple/Fn-typed field are all "no": each is stored as an
/// opaque pointer with no single correct comparison without the same
/// generic-erasure machinery item 200's own design sketch describes.
fn ty_is_comparable(te: &certo_ast::types::TypeExpr, shapes: &std::collections::HashMap<String, TypeShape<'_>>) -> bool {
    let mut visiting = std::collections::HashSet::new();
    ty_is_comparable_inner(te, shapes, &mut visiting)
}

/// The real recursive worker behind `ty_is_comparable` — split out purely
/// to thread `visiting` (BACKLOG item 259) without changing that function's
/// own two-arg call sites above. `visiting` is the set of type names whose
/// own field-comparability check is *currently in progress* on this call
/// stack — a self-referential sum type (`Node(left: Tree, right: Tree)`,
/// spec §3.3's own `Tree<T>` example, a perfectly valid recursive data
/// structure since a payload field needing heap-boxing is already stored as
/// a pointer in C, not inline) previously recursed into the exact same
/// `ty_is_comparable(Tree, shapes)` call forever — a real, direct Rust
/// stack overflow in the compiler itself, confirmed live via `certo build`
/// on the spec's own example. Hitting a name already in `visiting` means a
/// cycle was found before any base case — conservatively "not comparable"
/// (matching this function's own already-established conservative stance
/// for anything without a single correct comparison), not a crash.
fn ty_is_comparable_inner(
    te: &certo_ast::types::TypeExpr,
    shapes: &std::collections::HashMap<String, TypeShape<'_>>,
    visiting: &mut std::collections::HashSet<String>,
) -> bool {
    use certo_ast::types::TypeExpr;
    match te {
        TypeExpr::Named { path, args, .. } => {
            if !args.is_empty() { return false; } // List<T>/Map<K,V>/a user generic instantiation
            let name = path.segments.last().map(|s| s.node.as_str()).unwrap_or("");
            match name {
                "Int" | "Float" | "Bool" | "Unit" | "Text" | "BoundedText" | "Decimal" | "UUID" => true,
                _ if visiting.contains(name) => false,
                _ => match shapes.get(name) {
                    Some(TypeShape::Record(fields)) => {
                        visiting.insert(name.to_string());
                        let result = fields.iter().all(|f| !f.optional && ty_is_comparable_inner(&f.ty.node, shapes, visiting));
                        visiting.remove(name);
                        result
                    }
                    Some(TypeShape::NullaryEnum) => true,
                    Some(TypeShape::PayloadEnum(variants)) => {
                        visiting.insert(name.to_string());
                        let result = variants.iter().all(|v| v.fields.iter().all(|f| ty_is_comparable_inner(&f.ty.node, shapes, visiting)));
                        visiting.remove(name);
                        result
                    }
                    None => false, // unknown name (a stdlib opaque type like DateTime, or truly undeclared)
                }
            }
        }
        TypeExpr::DecimalParam { .. } => true,
        TypeExpr::BoundedTextParam { .. } => true,
        _ => false, // Option/Tuple/Fn/anonymous Record/Ptr/Param — not comparable
    }
}

/// The C expression comparing `a`/`b` of this type — only ever called
/// after `ty_is_comparable` has already confirmed it's possible.
fn emit_field_cmp(a: &str, b: &str, te: &certo_ast::types::TypeExpr, shapes: &std::collections::HashMap<String, TypeShape<'_>>) -> String {
    use certo_ast::types::TypeExpr;
    match te {
        TypeExpr::Named { path, .. } => {
            let name = path.segments.last().map(|s| s.node.as_str()).unwrap_or("");
            match name {
                "Text" | "BoundedText" => format!("certo_text_eq({a}, {b})"),
                "UUID" => format!("certo_uuid_eq({a}, {b})"),
                "Decimal" => format!("certo_decimal_eq({a}, {b})"),
                _ => match shapes.get(name) {
                    Some(TypeShape::Record(_)) | Some(TypeShape::PayloadEnum(_)) =>
                        format!("certo_eq_{}({a}, {b})", c_ident(name)),
                    _ => format!("({a} == {b})"), // Int/Float/Bool/Unit, or a nullary enum (already a plain int)
                }
            }
        }
        TypeExpr::DecimalParam { .. } => format!("certo_decimal_eq({a}, {b})"),
        TypeExpr::BoundedTextParam { .. } => format!("certo_text_eq({a}, {b})"),
        _ => unreachable!("emit_field_cmp called on a type ty_is_comparable rejected"),
    }
}

fn ast_ty_to_c_str(te: &certo_ast::types::TypeExpr) -> String {
    use certo_ast::types::TypeExpr;
    match te {
        TypeExpr::Named { path, args, .. } => {
            // Any generic instantiation — a built-in (`List<Int>`, `Map<K,V>`,
            // an explicit `Option<T>`/`Result<A,B>`) or a user's own
            // (`Box<T>`) — is an opaque pointer everywhere else in codegen
            // (`ty_to_c` on the resolved `Ty`); a bare `Named` name lookup
            // below would either hit the wrong branch or fall through to a
            // literal (and undeclared) C type name like `List`.
            if !args.is_empty() { return "void*".into(); }
            let name = path.segments.last().map(|s| s.node.as_str()).unwrap_or("void");
            match name {
                "Int"     => "int64_t".into(),
                "Float"   => "double".into(),
                "Decimal" => "certo_decimal_t".into(),
                "Bool"    => "bool".into(),
                "Text"    => "certo_text_t".into(),
                "BoundedText" => "certo_text_t".into(),
                "Unit"    => "certo_unit_t".into(),
                "UUID"    => "certo_uuid_t".into(),
                // These stdlib scalar types have a C-side typedef prefixed
                // `Certo` (`CertoDateTime`, etc.) rather than matching their
                // bare Certo name — the same gap `ty_to_c.rs` (the
                // resolved-`Ty` version of this function) already fixed, but
                // this separate AST-level copy (used for `type X = { ... }`
                // record *field* declarations specifically) never got the
                // same fix, so a `DateTime`/`Date`/`Duration`-typed field
                // emitted the literal, undeclared C identifier `DateTime`
                // instead — confirmed via a real `certo db pull`-generated
                // struct with a `createdAt: DateTime` field failing to
                // compile (BACKLOG item 134, found while verifying the
                // struct-boxing fix end-to-end, not caused by it).
                // BACKLOG item 317 — `Timestamp` was missing from this list
                // (present in `ty_to_c.rs`'s own identical match, item 164,
                // ever since), so a record *field* typed `Timestamp`
                // (unlike a function param/return, which already went
                // through `ty_to_c.rs`) emitted the bare, undeclared C
                // identifier `Timestamp` — confirmed via a real struct
                // definition with a `dueAt: Timestamp` field failing to
                // compile. `Timestamp` has no separate runtime type of its
                // own (see `ty_to_c.rs`'s own doc comment) — reuses
                // `CertoDateTime` exactly, same as there.
                "DateTime" | "Date" | "Duration" | "Timezone" => format!("Certo{}", name),
                "Timestamp" => "CertoDateTime".to_string(),
                "JsonValue" | "ProcessResult" => format!("Certo{}*", name),
                other     => c_ident(other),
            }
        }
        // `T?` — matches the internal nullable-pointer Option representation
        // used everywhere else (`ty_to_c(Ty::Option(_)) => "void*"`), not the
        // separate ABI-stable `certo_option_t` struct crates/ffi's header
        // generator deliberately uses instead for its public-facing API.
        TypeExpr::Option { .. }  => "void*".into(),
        TypeExpr::Tuple { elements, .. } => {
            if elements.is_empty() { "int64_t".into() } else { "void*".into() }
        }
        TypeExpr::Fn { .. }      => "certo_fn_t".into(),
        TypeExpr::Record { .. }  => "void*".into(),
        TypeExpr::Ptr { inner, .. } => format!("{}*", ast_ty_to_c_str(&inner.node)),
        TypeExpr::Param { .. }   => "void*".into(),
        // Same runtime representation as bare `Decimal` — the parameter is a
        // compile-time-only refinement.
        TypeExpr::DecimalParam { .. } => "certo_decimal_t".into(),
        // Same runtime representation as bare `Text` — the max length is a
        // compile-time-only refinement (BACKLOG item 147).
        TypeExpr::BoundedTextParam { .. } => "certo_text_t".into(),
    }
}

/// A field's C type, aware of the enclosing `type`'s own declared type
/// parameters (`type Box<T> = { value: T }`'s `T`) — BACKLOG item 119. The
/// parser never actually constructs `TypeExpr::Param` (verified dead code),
/// so a bare type-param reference always parses as an ordinary
/// `TypeExpr::Named` with an empty-args, single-segment path; `ast_ty_to_c_str`
/// alone has no way to tell that apart from a real (and here, undeclared) type
/// name. Its C storage is `void*` regardless of what it's instantiated to,
/// matching how `crates/mir/src/lower.rs` heap-boxes/unboxes such fields.
/// `self_ref_name` is `Some(parent_type_name)` only when called for a
/// sum-type variant's own field — BACKLOG item 277: a *direct* self-
/// referential field (e.g. `Node(left: Tree, right: Tree)`, where `left`'s
/// declared type is `Tree`, `Node`'s own enclosing type) can't be embedded
/// inline-by-value the way an ordinary nested field is — that's an
/// infinite-size C struct — so it's stored as a pointer instead. The value
/// itself is never exposed as a raw pointer to Certo source: construction
/// heap-boxes it (MIR's call-site argument lowering) and pattern-matching
/// dereferences it back to a plain value (MIR's field-binding lowering).
fn field_c_ty(te: &certo_ast::types::TypeExpr, type_params: &[String], self_ref_name: Option<&str>) -> String {
    if let certo_ast::types::TypeExpr::Named { path, args, .. } = te {
        if args.is_empty() && path.segments.len() == 1 {
            if let Some(seg) = path.segments.first() {
                if type_params.iter().any(|p| p == &seg.node) {
                    return "void*".into();
                }
                if self_ref_name == Some(seg.node.as_str()) {
                    // `struct {name}*`, not the bare `{name}*` typedef alias
                    // — at this point in the generated C, we're still
                    // *inside* the `typedef struct {name} { ... } {name};`
                    // that declares this very type, so only its struct tag
                    // (added specifically for this case, see the `TypeBody::
                    // Sum` arm above) is a valid type name yet; the typedef
                    // alias itself isn't usable until that whole statement
                    // completes.
                    return format!("struct {}*", c_ident(&seg.node));
                }
            }
        }
    }
    ast_ty_to_c_str(te)
}

fn const_expr_to_c(expr: &certo_hir::HirExpr) -> String {
    use certo_hir::HirExprKind;
    match &expr.kind {
        HirExprKind::Int(n)     => n.to_string(),
        HirExprKind::Float(f)   => format!("{:.}", f),
        HirExprKind::Bool(b)    => if *b { "true".into() } else { "false".into() },
        HirExprKind::Str(s)     => {
            let escaped: String = s.chars().flat_map(|c| match c {
                '\n' => vec!['\\', 'n'],
                '\r' => vec!['\\', 'r'],
                '\t' => vec!['\\', 't'],
                '\\' => vec!['\\', '\\'],
                '"'  => vec!['\\', '"'],
                c    => vec![c],
            }).collect();
            format!("CERTO_STR(\"{}\")", escaped)
        }
        HirExprKind::Unit       => "CERTO_UNIT".into(),
        _                       => "/* expr */0".into(),
    }
}

fn const_expr_ty(expr: &certo_hir::HirExpr) -> String {
    use certo_hir::HirExprKind;
    match &expr.kind {
        HirExprKind::Int(_)   => "int64_t".into(),
        HirExprKind::Float(_) => "double".into(),
        HirExprKind::Bool(_)  => "bool".into(),
        HirExprKind::Str(_)   => "certo_text_t".into(),
        HirExprKind::Unit     => "int64_t".into(),
        _                     => "void*".into(),
    }
}

/// Attempt to convert a simple Certo AST expression to a C statement string.
/// Returns `None` for complex expressions that require HIR lowering.
fn simple_expr_to_c(expr: &certo_ast::expr::Expr) -> Option<String> {
    use certo_ast::expr::Expr;
    match expr {
        // fn_name(args...) where args are simple
        Expr::App { func, args, .. } => {
            let fname = match &func.node {
                Expr::Path { path, .. } => {
                    path.segments.iter()
                        .map(|s| s.node.as_str())
                        .collect::<Vec<_>>()
                        .join(".")
                }
                _ => return None,
            };
            let c_fn = c_fn_name(&fname);
            let c_args: Option<Vec<String>> = args.iter()
                .map(|a| simple_expr_to_c_rvalue(&a.value.node))
                .collect();
            Some(format!("{}({})", c_fn, c_args?.join(", ")))
        }
        _ => None,
    }
}

fn simple_expr_to_c_rvalue(expr: &certo_ast::expr::Expr) -> Option<String> {
    use certo_ast::expr::{Expr, Lit};
    match expr {
        Expr::Lit { value, .. } => match value {
            Lit::String(s) => {
                let e: String = s.chars().flat_map(|c| match c {
                    '\n' => vec!['\\', 'n'],
                    '\r' => vec!['\\', 'r'],
                    '\t' => vec!['\\', 't'],
                    '\\' => vec!['\\', '\\'],
                    '"'  => vec!['\\', '"'],
                    c    => vec![c],
                }).collect();
                Some(format!("CERTO_STR(\"{}\")", e))
            }
            Lit::Int(n)    => Some(n.to_string()),
            Lit::Float(f)  => Some(f.to_string()),
            Lit::Bool(b)   => Some(if *b { "true".into() } else { "false".into() }),
            _ => None,
        },
        Expr::Path { path, .. } => {
            if path.segments.len() == 1 {
                Some(path.segments[0].node.clone())
            } else {
                None
            }
        }
        _ => None,
    }
}

// ------------------------------------------------------------------ //
// Embedded runtime header
// ------------------------------------------------------------------ //

pub const RUNTIME_HEADER: &str = r#"
#include <stdlib.h>
/* ---- DLL export attribute ---- */
#ifdef _WIN32
#  define CERTO_EXPORT __declspec(dllexport)
#else
#  define CERTO_EXPORT __attribute__((visibility("default")))
#endif

/* ---- Certo runtime types ---- */
typedef int64_t      certo_int_t;
typedef double       certo_float_t;
typedef const char*  certo_text_t;
typedef bool         certo_bool_t;

typedef struct { int _unused; } certo_unit_t;
#define CERTO_UNIT ((certo_unit_t){0})

/* Decimal: stored as scaled integer (cents × 10^scale). */
typedef struct { int64_t value; int8_t scale; } certo_decimal_t;
#define CERTO_DECIMAL(s) certo_decimal_parse(s)
certo_decimal_t certo_decimal_parse(const char* s);

/* Text */
#define CERTO_STR(s) ((certo_text_t)(s))
certo_text_t certo_text_concat(certo_text_t a, certo_text_t b);
int64_t      certo_text_len(certo_text_t t);
bool         certo_text_eq(certo_text_t a, certo_text_t b);

/* UUID */
typedef struct { uint8_t bytes[16]; } certo_uuid_t;
#define CERTO_UUID(s) certo_uuid_parse(s)
certo_uuid_t certo_uuid_parse(const char* s);
certo_uuid_t certo_uuid_new(void);
certo_uuid_t* certo_parse_uuid(certo_text_t s);   /* BACKLOG item 228 */
certo_text_t  certo_uuid_to_text(certo_uuid_t u); /* BACKLOG item 228 */

/* Generic option (pointer-sized tag + value) */
typedef struct { bool has_value; void* value; } certo_option_t;
/* Option: None is a null pointer; Some is a heap pointer to an 8-byte payload
   slot. This lets Some(0) differ from None and preserves Float bit patterns.
   `Some(v)` in Certo lowers to a typed heap box; stdlib producers use the
   helper below (which stores raw pointer-sized bits). Match/unwrap dereferences. */
#define certo_none ((void*)0)
static inline void* __certo_opt_box(int64_t bits) {
    int64_t* p = (int64_t*)malloc(sizeof(int64_t));
    *p = bits;
    return p;
}
/* Bit-preserving casts double<->int64: a `double` must not be numeric-converted
   when it passes through a pointer-sized payload slot (Result payload, etc.). */
static inline int64_t __certo_f2i(double d) { union { double d; int64_t i; } u; u.d = d; return u.i; }
static inline double  __certo_i2f(int64_t i) { union { double d; int64_t i; } u; u.i = i; return u.d; }
/* Fallback for any stray `Some(x)` not lowered to a typed box (heap-boxes bits). */
#define certo_some(x) __certo_opt_box((int64_t)(x))
typedef struct { void* value; } certo_tuple_t;
/* A Certo function *value* — real closure capture (BACKLOG item 140).
 * `fn` is the lambda's own generated C function (or a plain named function
 * wrapped with `env = NULL`), which always takes its closure environment as
 * an explicit leading parameter, whether or not it actually captures
 * anything — so caller and callee always agree on arity. `env` is a heap
 * tuple (a `CertoList*`, same representation an ordinary Certo tuple/list
 * literal already uses) holding the boxed captured values, or NULL when
 * there are none. Passed by value (16 bytes on a 64-bit target) wherever a
 * `Ty::Fn` value flows — see `ty_to_c`. */
typedef struct { void* fn; void* env; } certo_fn_t;
typedef void* certo_error_t;

/* List (dynamic array) — full signatures are in the stdlib C block. */
typedef struct { int64_t len; int64_t cap; void** data; } certo_list_base_t;
/* certo_list_empty/certo_map_empty (List.empty()/Map.empty()) are real functions
   defined alongside CertoList/CertoMap in the stdlib C block, not macros here —
   see crates/stdlib/src/collections.rs. */

/* Result<T,E> — heap-allocated tagged value.
   payload stores any scalar (int/float/bool) or pointer cast to intptr_t.
   On 64-bit platforms intptr_t == int64_t, so all Certo value types fit. */
typedef struct { bool is_ok; intptr_t payload; } certo_result_t;

static inline void* certo_ok(intptr_t v) {
    certo_result_t* r = (certo_result_t*)malloc(sizeof(certo_result_t));
    r->is_ok = true;  r->payload = v; return r;
}
static inline void* certo_err(intptr_t e) {
    certo_result_t* r = (certo_result_t*)malloc(sizeof(certo_result_t));
    r->is_ok = false; r->payload = e; return r;
}
/* Intrinsics used by the ? desugaring in compiled code. */
static inline bool     __result_is_ok(void* r) { return ((certo_result_t*)r)->is_ok; }
static inline intptr_t __result_unwrap(void* r) { return ((certo_result_t*)r)->payload; }
static inline intptr_t __tuple_get(void* t, int64_t i) { return (intptr_t)((certo_list_base_t*)t)->data[i]; }

/* Arithmetic helpers */
int64_t certo_pow(int64_t base, int64_t exp);
void*   certo_coalesce(void* opt, void* fallback);

/* NULL constant used by Option pattern matching (cast to int64_t for comparison) */
#define __NULL ((int64_t)0)

/* Panic */
__attribute__((noreturn)) void certo_panic(certo_text_t msg);
#define certo_unreachable() certo_panic("unreachable")
#define certo_todo()        certo_panic("not yet implemented")

/* GUI — native message box */
#ifdef _WIN32
#  include <windows.h>
static inline int64_t certo_message_box(certo_text_t title, certo_text_t message) {
    MessageBoxA(NULL, (const char*)message, (const char*)title, MB_OK | MB_ICONINFORMATION);
    return 0;
}
#else
static inline int64_t certo_message_box(certo_text_t title, certo_text_t message) {
    /* Fallback: print to stderr on non-Windows */
    fprintf(stderr, "[%s] %s\n", (const char*)title, (const char*)message);
    return 0;
}
#endif

/* stdin */
void*   certo_read_line(void);   /* Option<Text> (heap-boxed) */
certo_text_t certo_read_all(void);

/* argv — call certo_main_init(argc, argv) at the top of main() */
void    certo_main_init(int argc, const char** argv);
int64_t certo_arg_count(void);
void*   certo_arg(int64_t i);    /* Option<Text> (heap-boxed) */

/* DB transaction — real implementation in crates/stdlib/src/db.rs's DB_C,
 * only linked in when CERTO_DB_ENABLED (BACKLOG item 226; crates/cli/src/
 * main.rs defines it whenever the module uses `db.transaction`/
 * `db.<table>.<method>` sugar, or an explicit `import Db`). This forward
 * declaration itself is harmless to always emit — it's just a prototype —
 * but the other two ambient-db symbols below are guarded, since ordinary
 * non-DB programs never define them and the guard keeps the two matched
 * (used only from within HTTP_C's own matching guard, crates/stdlib/src/
 * http.rs, which — unlike DB_C — is always linked in). */
void* __db_transaction(certo_fn_t thunk);
#ifdef CERTO_DB_ENABLED
int64_t __certo_db_conn(void);
void    __certo_db_thread_teardown(void);
#endif

/* Record update */
void* __record_update(void* base, void* updates);

/* ---- Concurrency: portable OS-thread shim ---- */
/* `parallel {}` / `spawn` / `await` lower to per-call-site worker functions that
   run on a real OS thread. Windows uses Win32 threads (no extra link flags);
   POSIX uses pthreads (compile/link with -pthread). */
typedef void* (*__certo_worker_fn)(void*);
#if defined(_WIN32)
  #include <windows.h>
  typedef HANDLE __certo_thread_t;
  typedef struct { __certo_worker_fn fn; void* arg; } __certo_tramp_t;
  static DWORD WINAPI __certo_win_trampoline(LPVOID _t) {
      __certo_tramp_t* t = (__certo_tramp_t*)_t;
      __certo_worker_fn fn = t->fn; void* arg = t->arg;
      free(t);
      fn(arg);
      return 0;
  }
  static __certo_thread_t __certo_thread_spawn(__certo_worker_fn fn, void* arg) {
      __certo_tramp_t* t = (__certo_tramp_t*)malloc(sizeof(__certo_tramp_t));
      t->fn = fn; t->arg = arg;
      return CreateThread(NULL, 0, __certo_win_trampoline, t, 0, NULL);
  }
  static void __certo_thread_join(__certo_thread_t th) {
      WaitForSingleObject(th, INFINITE);
      CloseHandle(th);
  }
  /* Fixed-layout task header — the common prefix of every spawn context struct.
     WaitForSingleObject already natively supports a millisecond timeout on
     the thread handle itself, so no extra completion signal is needed here.
     `state` backs `withTimeout`'s safe-abandonment protocol below. */
  typedef struct { __certo_thread_t thread; volatile int state; } __certo_task_hdr_t;
  static inline void __certo_task_hdr_init(__certo_task_hdr_t* hdr) { hdr->state = 0; }
  static inline void __certo_task_signal_done(__certo_task_hdr_t* hdr) { (void)hdr; }
  /* `parallel(timeout: ...) { ... }` — BACKLOG item 81. Returns true if the
     thread finished within `timeout_ms` (clamped to >= 0), false on timeout.
     On timeout the thread/handle are deliberately leaked: Certo has no
     thread-cancellation mechanism, and the caller panics immediately after,
     so the process is about to exit anyway. */
  static bool __certo_thread_join_timed(__certo_task_hdr_t* hdr, int64_t timeout_ms) {
      if (timeout_ms < 0) timeout_ms = 0;
      DWORD r = WaitForSingleObject(hdr->thread, (DWORD)timeout_ms);
      if (r == WAIT_OBJECT_0) { CloseHandle(hdr->thread); return true; }
      return false;
  }
  /* `withTimeout(d) { ... }` (BACKLOG item 122) — unlike `parallel(timeout:
     ...)` above, the caller must be able to continue past the deadline
     instead of panicking, so the worker thread can't just be leaked: it may
     go on running for an arbitrary time after the joiner gives up on it.
     Called by the worker's own trampoline once it loses the race (see
     `__certo_task_hdr_try_finish` below) to release the now-unjoinable
     thread handle itself. */
  static inline void __certo_task_hdr_abandon_cleanup(__certo_task_hdr_t* hdr) {
      CloseHandle(hdr->thread);
  }
#else
  #include <pthread.h>
  #include <semaphore.h>
  #include <time.h>
  typedef pthread_t __certo_thread_t;
  static __certo_thread_t __certo_thread_spawn(__certo_worker_fn fn, void* arg) {
      pthread_t th; pthread_create(&th, NULL, fn, arg); return th;
  }
  static void __certo_thread_join(__certo_thread_t th) { pthread_join(th, NULL); }
  /* Fixed-layout task header — the common prefix of every spawn context struct.
     `pthread_join` has no portable timeout (`pthread_timedjoin_np` is a
     Linux-only glibc extension), so a semaphore the worker posts on
     completion backs the portable timed wait below. `state` backs
     `withTimeout`'s safe-abandonment protocol below. */
  typedef struct { __certo_thread_t thread; sem_t done; volatile int state; } __certo_task_hdr_t;
  static inline void __certo_task_hdr_init(__certo_task_hdr_t* hdr) { sem_init(&hdr->done, 0, 0); hdr->state = 0; }
  static inline void __certo_task_signal_done(__certo_task_hdr_t* hdr) { sem_post(&hdr->done); }
  /* `parallel(timeout: ...) { ... }` — BACKLOG item 81. Returns true if the
     thread finished within `timeout_ms` (clamped to >= 0), false on timeout.
     On timeout the thread is deliberately leaked (not joined, semaphore not
     destroyed): Certo has no thread-cancellation mechanism, and the caller
     panics immediately after, so the process is about to exit anyway. */
  static bool __certo_thread_join_timed(__certo_task_hdr_t* hdr, int64_t timeout_ms) {
      if (timeout_ms < 0) timeout_ms = 0;
      struct timespec ts;
      clock_gettime(CLOCK_REALTIME, &ts);
      ts.tv_sec  += timeout_ms / 1000;
      ts.tv_nsec += (long)(timeout_ms % 1000) * 1000000L;
      if (ts.tv_nsec >= 1000000000L) { ts.tv_sec += 1; ts.tv_nsec -= 1000000000L; }
      if (sem_timedwait(&hdr->done, &ts) == 0) { pthread_join(hdr->thread, NULL); return true; }
      return false;
  }
  /* `withTimeout(d) { ... }` (BACKLOG item 122) — see the Win32 branch's own
     comment above for why leaking (item 81's approach) isn't safe here. A
     pthread can't be joined by the thread it belongs to, but it *can*
     detach itself — after which the OS reclaims its resources on exit with
     no join required from anyone. */
  static inline void __certo_task_hdr_abandon_cleanup(__certo_task_hdr_t* hdr) {
      (void)hdr;
      pthread_detach(pthread_self());
  }
#endif
/* `withTimeout`'s safe-abandonment protocol (BACKLOG item 122): a task's
   `hdr.state` transitions exactly once, from 0 ("running") to either 1
   ("abandoned by a timed-out joiner — the worker frees the context itself
   once it finishes instead of signaling completion") or 2 ("finished
   normally by the worker — the joiner's usual read-then-free path
   applies"). Both transitions are attempted via the same atomic
   compare-and-swap, so exactly one side ever wins regardless of whether the
   joiner's deadline or the worker's own completion comes first — the loser
   simply takes the other branch instead of touching the context again. This
   needs no platform split: `__sync_bool_compare_and_swap` is a compiler
   (not OS) intrinsic, available identically under both branches above. */
static inline bool __certo_task_hdr_try_abandon(__certo_task_hdr_t* hdr) {
    return __sync_bool_compare_and_swap(&hdr->state, 0, 1);
}
static inline bool __certo_task_hdr_try_finish(__certo_task_hdr_t* hdr) {
    return __sync_bool_compare_and_swap(&hdr->state, 0, 2);
}
/* A lifted spawn worker's own cooperative-cancellation checkpoint (BACKLOG
   item 186), called at each loop back-edge with its own header pointer
   (passed by the spawn trampoline — `emit_spawn_support`). Reading `state`
   here never races with the CAS functions above: this only ever runs on
   the worker's own thread, the only thread that can observe `state == 1`
   (abandoned) without itself having caused that transition, and `state` is
   `volatile` so this read is never cached stale across the loop. */
static inline bool __certo_task_hdr_is_abandoned(__certo_task_hdr_t* hdr) {
    return hdr->state == 1;
}
/* ---- end Certo runtime ---- */
"#;
