[package]
name    = "certo"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "certo"
path = "src/main.rs"

[dependencies]
certo-ast         = { path = "../ast" }
certo-fmt         = { path = "../fmt" }
certo-testrunner  = { path = "../testrunner" }
certo-parser      = { path = "../parser" }
certo-migrate     = { path = "../migrate" }
certo-codegen     = { path = "../codegen" }
certo-stdlib      = { path = "../stdlib" }
certo-diagnostics = { path = "../diagnostics" }
certo-typeck      = { path = "../typeck" }
tempfile          = "3"
