[package]
name    = "certo"
version = "1.0.59"
edition = "2024"

[[bin]]
name = "certo"
path = "src/main.rs"

[dependencies]
certo-ast         = { path = "../ast" }
certo-hir         = { path = "../hir" }
certo-fmt         = { path = "../fmt" }
certo-testrunner  = { path = "../testrunner" }
certo-parser      = { path = "../parser" }
certo-migrate     = { path = "../migrate" }
certo-codegen     = { path = "../codegen" }
certo-stdlib      = { path = "../stdlib" }
certo-diagnostics = { path = "../diagnostics" }
certo-typeck      = { path = "../typeck" }
certo-traits      = { path = "../traits" }
certo-dbschema    = { path = "../dbschema" }
certo-effects     = { path = "../effects" }
certo-ui          = { path = "../ui" }
tempfile          = "3"
serde             = { version = "1", features = ["derive"] }
serde_yaml        = "0.9"
toml              = "0.8"
toml_edit         = "0.22"

[build-dependencies]
winres = "0.1"
