//! MySQL 8 lowering (8.0.16 or later: it needs `CHECK`). Identifiers are backtick-quoted.
//!
//! Where MySQL differs from PostgreSQL and SQLite, this either makes it behave the same or refuses with a reason:
//!
//! * Every table is `utf8mb4` with the binary collation (`utf8mb4_bin`), so text is compared and made unique exactly,
//!   as it is on the others (MySQL's default collation ignores case).
//! * `text`, `json` and `bytes` columns cannot be a key or in an index (MySQL wants a prefix length, which would change
//!   what unique means): refused, use `varchar(n)`.
//! * Enums are written inline (`ENUM('a','b')`) on each column that uses them; the enum's name travels in a column
//!   comment (`certo:enum Name`) so a database can be read back. `uuid` is `CHAR(36)` and `timestamp` (with time
//!   zone) is `DATETIME(6)` holding UTC, each tagged the same way (`certo:uuid`, `certo:timestamptz`).
//! * `serial` and `generated by default` are both `AUTO_INCREMENT`; `generated always` is refused (MySQL lets you
//!   write the value). Sequences and composite types do not exist.
//! * Defaults are always written as expressions (`DEFAULT (...)`), which MySQL accepts for every type.
//! * DDL commits by itself, so nothing is transactional: every statement is its own batch.
//!
//! Naming matches PostgreSQL's where MySQL allows it: unique `<table>_<col>_key`, foreign key `fk_<table>_<col>`;
//! the primary key is MySQL's own `PRIMARY`. Index and CHECK names are the SDL names.

use crate::{unsupported, Batch, LowerError, Schemas};
use certo_mdl::{action_sql, EnumColumn, MigrationPlan, Op, VariantMapping};
use certo_sdl::{BinaryOp, Builtin, ColumnIR, ExprIR, ForeignKeyIR, Generation, ReferentialAction, TableIR, TypeIR};

pub(crate) fn q(ident: &str) -> String {
    format!("`{}`", ident.replace('`', "``"))
}

/// MySQL reads a backslash in a string as an escape.
pub(crate) fn lit(s: &str) -> String {
    format!("'{}'", s.replace('\\', "\\\\").replace('\'', "''"))
}

/// The column type, with `variants` for an enum.
pub(crate) fn ty(t: &TypeIR, variants: Option<&[String]>) -> String {
    match t {
        TypeIR::Builtin(b) => match b {
            Builtin::Text => "LONGTEXT".into(),
            Builtin::SmallInt => "SMALLINT".into(),
            Builtin::Int => "INT".into(),
            Builtin::BigInt => "BIGINT".into(),
            // unconstrained `numeric` has no MySQL spelling: the widest one is the nearest thing
            Builtin::Decimal => "DECIMAL(65,30)".into(),
            Builtin::Real => "FLOAT".into(),
            Builtin::Float => "DOUBLE".into(),
            Builtin::Bool => "BOOLEAN".into(),
            Builtin::Uuid => "CHAR(36)".into(),
            Builtin::Timestamp | Builtin::TimestampNaive => "DATETIME(6)".into(),
            Builtin::Date => "DATE".into(),
            Builtin::Json => "JSON".into(),
            Builtin::Bytes => "LONGBLOB".into(),
            Builtin::Varchar(n) => format!("VARCHAR({n})"),
            Builtin::Char(n) => format!("CHAR({n})"),
            Builtin::Numeric(p, s) => format!("DECIMAL({p},{s})"),
        },
        TypeIR::Enum(_) => {
            let vs: Vec<String> = variants.unwrap_or_default().iter().map(|v| lit(v)).collect();
            format!("ENUM({})", vs.join(","))
        }
        TypeIR::Composite(_) => "JSON".into(),
    }
}

/// The comment that says what a column is when its MySQL type alone does not (`None`: nothing to say).
pub(crate) fn tag(t: &TypeIR) -> Option<String> {
    match t {
        TypeIR::Builtin(Builtin::Uuid) => Some("certo:uuid".into()),
        TypeIR::Builtin(Builtin::Timestamp) => Some("certo:timestamptz".into()),
        TypeIR::Enum(n) => Some(format!("certo:enum {n}")),
        _ => None,
    }
}

const UUID_V4: &str = "LOWER(CONCAT(HEX(RANDOM_BYTES(4)), '-', HEX(RANDOM_BYTES(2)), '-4', SUBSTR(HEX(RANDOM_BYTES(2)), 2), '-', \
SUBSTR('89ab', FLOOR(1 + RAND() * 4), 1), SUBSTR(HEX(RANDOM_BYTES(2)), 2), '-', HEX(RANDOM_BYTES(6))))";

pub(crate) fn expr(e: &ExprIR) -> Result<String, String> {
    Ok(match e {
        ExprIR::Raw { sql } => sql.clone(),
        ExprIR::Number { value } if *value < 0 => format!("({value})"),
        ExprIR::Number { value } => value.to_string(),
        ExprIR::Decimal { value } if value.starts_with('-') => format!("({value})"),
        ExprIR::Decimal { value } => value.clone(),
        ExprIR::IsNull { expr: inner, negated } => {
            format!("({} IS {}NULL)", expr(inner)?, if *negated { "NOT " } else { "" })
        }
        ExprIR::Not { expr: inner } => format!("(NOT {})", expr(inner)?),
        ExprIR::In { expr: inner, list, negated } => {
            let items = list.iter().map(expr).collect::<Result<Vec<_>, _>>()?;
            format!("({} {}IN ({}))", expr(inner)?, if *negated { "NOT " } else { "" }, items.join(", "))
        }
        ExprIR::String { value } => lit(value),
        ExprIR::Bool { value } => if *value { "TRUE" } else { "FALSE" }.to_string(),
        ExprIR::Column { name } => q(name),
        ExprIR::EnumVariant { variant, .. } => lit(variant),
        ExprIR::NextVal { .. } => return Err("MySQL has no sequences (`nextval`)".into()),
        ExprIR::Call { func, args } => match func.as_str() {
            "today" => "UTC_DATE()".to_string(),
            "now" => "UTC_TIMESTAMP(6)".to_string(),
            "gen_uuid" => UUID_V4.to_string(),
            "is_null" => format!("({} IS NULL)", expr(&args[0])?),
            // MySQL's LENGTH counts bytes
            "length" => format!("CHAR_LENGTH({})", expr(&args[0])?),
            other => {
                let args = args.iter().map(expr).collect::<Result<Vec<_>, _>>()?;
                format!("{other}({})", args.join(", "))
            }
        },
        ExprIR::Binary { op, lhs, rhs } => {
            let o = match op {
                BinaryOp::Eq => "=",
                BinaryOp::Ne => "<>",
                BinaryOp::Lt => "<",
                BinaryOp::Le => "<=",
                BinaryOp::Gt => ">",
                BinaryOp::Ge => ">=",
                BinaryOp::Add => "+",
                BinaryOp::Sub => "-",
                BinaryOp::Mul => "*",
                BinaryOp::Div => "/",
                BinaryOp::And => "AND",
                BinaryOp::Or => "OR",
            };
            format!("({} {o} {})", expr(lhs)?, expr(rhs)?)
        }
    })
}

fn unique_name(table: &str, col: &str) -> String { format!("{table}_{col}_key") }
fn fk_name(table: &str, col: &str) -> String { format!("fk_{table}_{col}") }

/// Can MySQL index a column of this type without a prefix length?
fn indexable(t: &TypeIR) -> bool {
    !matches!(t, TypeIR::Builtin(Builtin::Text | Builtin::Json | Builtin::Bytes) | TypeIR::Composite(_))
}

struct Cx<'a> {
    schemas: &'a Schemas<'a>,
}

type R<T> = Result<T, String>;

impl Cx<'_> {
    fn variants(&self, name: &str) -> R<&[String]> {
        self.schemas
            .new
            .enums
            .iter()
            .find(|e| e.name == name)
            .map(|e| e.variants.as_slice())
            .ok_or_else(|| format!("enum `{name}` is not in the new schema"))
    }

    /// The column's type text, with the enum's values spelled out.
    fn column_type(&self, c: &ColumnIR) -> R<String> {
        match &c.ty {
            TypeIR::Enum(n) => Ok(ty(&c.ty, Some(self.variants(n)?))),
            TypeIR::Composite(_) => Err(format!("column `{}` has a composite type, which MySQL does not have", c.name)),
            t => Ok(ty(t, None)),
        }
    }

    /// `` `col` TYPE NULL|NOT NULL [AUTO_INCREMENT] [DEFAULT (..)] [COMMENT '..'] ``.
    fn column_def(&self, c: &ColumnIR) -> R<String> {
        let mut s = format!("{} {}", q(&c.name), self.column_type(c)?);
        s.push_str(if c.nullable { " NULL" } else { " NOT NULL" });
        match c.generated {
            Some(Generation::Always) => {
                return Err(format!(
                    "column `{}` is `generated always`, which MySQL cannot enforce (AUTO_INCREMENT lets you write the value); use `serial` or `generated by default`",
                    c.name
                ));
            }
            Some(_) => s.push_str(" AUTO_INCREMENT"),
            None => {}
        }
        if let Some(d) = &c.default {
            s.push_str(&format!(" DEFAULT ({})", expr(d)?));
        }
        if let Some(t) = tag(&c.ty) {
            s.push_str(&format!(" COMMENT {}", lit(&t)));
        }
        Ok(s)
    }

    fn create_table(&self, t: &TableIR) -> R<String> {
        let mut parts = Vec::new();
        for c in &t.columns {
            parts.push(self.column_def(c)?);
        }
        let pks: Vec<&ColumnIR> = t.columns.iter().filter(|c| c.primary_key).collect();
        for c in pks.iter().copied().chain(t.columns.iter().filter(|c| c.unique && !c.primary_key)) {
            if !indexable(&c.ty) {
                return Err(index_refusal(&t.name, &c.name, &c.ty));
            }
        }
        if !pks.is_empty() {
            let cols: Vec<String> = pks.iter().map(|c| q(&c.name)).collect();
            parts.push(format!("PRIMARY KEY ({})", cols.join(", ")));
        }
        for c in t.columns.iter().filter(|c| c.unique && !c.primary_key) {
            parts.push(format!("CONSTRAINT {} UNIQUE ({})", q(&unique_name(&t.name, &c.name)), q(&c.name)));
        }
        let body: Vec<String> = parts.iter().map(|p| format!("    {p}")).collect();
        Ok(format!(
            "CREATE TABLE {} (\n{}\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;",
            q(&t.name),
            body.join(",\n")
        ))
    }

    /// The column as the new schema has it (what a `MODIFY COLUMN` must restate in full).
    fn new_column(&self, table: &str, c: &ColumnIR) -> ColumnIR {
        self.schemas.new.table(table).and_then(|t| t.column(&c.name)).cloned().unwrap_or_else(|| c.clone())
    }

    fn modify(&self, table: &str, c: &ColumnIR) -> R<String> {
        Ok(format!("ALTER TABLE {} MODIFY COLUMN {};", q(table), self.column_def(c)?))
    }
}

fn index_refusal(table: &str, col: &str, t: &TypeIR) -> String {
    let what = match t {
        TypeIR::Builtin(Builtin::Json) => "json",
        TypeIR::Builtin(Builtin::Bytes) => "bytes",
        _ => "text",
    };
    format!("`{table}.{col}` is {what}, which MySQL cannot index without a prefix length (that would change what unique means): use varchar(n)")
}

fn fk_clause(r: &ForeignKeyIR) -> String {
    let mut s = String::new();
    for (kw, a) in [("DELETE", r.on_delete), ("UPDATE", r.on_update)] {
        if a != ReferentialAction::NoAction {
            s.push_str(&format!(" ON {kw} {}", action_sql(a)));
        }
    }
    s
}

fn add_fk(table: &str, col: &str, r: &ForeignKeyIR) -> String {
    format!(
        "ALTER TABLE {} ADD CONSTRAINT {} FOREIGN KEY ({}) REFERENCES {} ({}){};",
        q(table), q(&fk_name(table, col)), q(col), q(&r.table), q(&r.column), fk_clause(r)
    )
}

fn raw_sql(sql: &str) -> String {
    let s = sql.trim();
    if s.ends_with(';') { s.to_string() } else { format!("{s};") }
}

/// `UPDATE t SET col = to WHERE col = from` for every mapping and column.
fn remap(mappings: &[VariantMapping], columns: &[EnumColumn], out: &mut Vec<String>) {
    for m in mappings {
        for c in columns {
            out.push(format!(
                "UPDATE {} SET {col} = {} WHERE {col} = {};",
                q(&c.table), lit(&m.to), lit(&m.from), col = q(&c.column.name)
            ));
        }
    }
}

fn lower_op(cx: &Cx, op: &Op, out: &mut Vec<String>) -> Result<(), LowerError> {
    let fail = |why: String| unsupported(op, why);
    match op {
        // an enum is part of each column that uses it: nothing to create or drop on its own
        Op::CreateEnum { .. } | Op::DropEnum { .. } => {}
        Op::AddEnumVariant { name, .. } | Op::RemoveEnumVariant { name, .. } => {
            // the columns that exist now and use it are redefined with the new values
            for t in &cx.schemas.old.tables {
                for c in &t.columns {
                    if matches!(&c.ty, TypeIR::Enum(n) if n == name) {
                        let new = cx.new_column(&t.name, c);
                        out.push(cx.modify(&t.name, &new).map_err(fail)?);
                    }
                }
            }
        }
        Op::RecreateEnum { mappings, columns, .. } => {
            remap(mappings, columns, out);
            for c in columns {
                let new = cx.new_column(&c.table, &c.column);
                out.push(cx.modify(&c.table, &new).map_err(fail)?);
            }
        }

        Op::CreateSequence { .. } | Op::AlterSequence { .. } | Op::DropSequence { .. } => {
            return Err(fail("MySQL has no sequences; use a `serial` column".into()));
        }
        Op::CreateType { .. } | Op::AlterType { .. } | Op::DropType { .. } => {
            return Err(fail("MySQL has no composite types".into()));
        }

        Op::CreateTable { definition } => {
            let t = cx.schemas.new.table(&definition.name).unwrap_or(definition);
            let mut def = definition.clone();
            def.columns = t.columns.iter().map(|c| ColumnIR { references: None, ..c.clone() }).collect();
            out.push(cx.create_table(&def).map_err(fail)?);
        }
        Op::DropTable { name } => out.push(format!("DROP TABLE {};", q(name))),

        Op::CreateView { definition: v } => {
            let cols: Vec<String> = v.columns.iter().map(|c| q(c)).collect();
            let mut s = format!("CREATE VIEW {} AS SELECT {} FROM {}", q(&v.name), cols.join(", "), q(&v.from));
            if let Some(f) = &v.filter {
                s.push_str(&format!(" WHERE {}", expr(f).map_err(fail)?));
            }
            out.push(s + ";");
        }
        Op::DropView { name } => out.push(format!("DROP VIEW {};", q(name))),

        Op::AddColumn { table, column } => {
            let def = cx.column_def(column).map_err(fail)?;
            if column.primary_key {
                // an AUTO_INCREMENT column must be a key the moment it exists
                out.push(format!("ALTER TABLE {} ADD COLUMN {def}, ADD PRIMARY KEY ({});", q(table), q(&column.name)));
            } else {
                out.push(format!("ALTER TABLE {} ADD COLUMN {def};", q(table)));
                if column.unique {
                    if !indexable(&column.ty) {
                        return Err(fail(index_refusal(table, &column.name, &column.ty)));
                    }
                    out.push(format!(
                        "ALTER TABLE {} ADD CONSTRAINT {} UNIQUE ({});",
                        q(table), q(&unique_name(table, &column.name)), q(&column.name)
                    ));
                }
            }
        }
        Op::AlterColumn { table, before, after } => {
            if before.primary_key != after.primary_key {
                return Err(fail("changing a primary key needs a hand-written migration".into()));
            }
            // existing NULLs would make NOT NULL fail; the column's own default is the only sensible fill
            if before.nullable && !after.nullable
                && let Some(d) = &after.default
            {
                out.push(format!(
                    "UPDATE {} SET {c} = {} WHERE {c} IS NULL;",
                    q(table), expr(d).map_err(fail)?, c = q(&after.name)
                ));
            }
            let (mut b, mut a) = (before.clone(), after.clone());
            b.unique = false;
            a.unique = false;
            b.references = None;
            a.references = None;
            if b != a {
                out.push(cx.modify(table, after).map_err(fail)?);
            }
            if before.unique != after.unique {
                let name = unique_name(table, &after.name);
                if after.unique {
                    if !indexable(&after.ty) {
                        return Err(fail(index_refusal(table, &after.name, &after.ty)));
                    }
                    out.push(format!("ALTER TABLE {} ADD CONSTRAINT {} UNIQUE ({});", q(table), q(&name), q(&after.name)));
                } else {
                    out.push(format!("ALTER TABLE {} DROP INDEX {};", q(table), q(&name)));
                }
            }
        }
        Op::DropColumn { table, name } => out.push(format!("ALTER TABLE {} DROP COLUMN {};", q(table), q(name))),

        Op::AddForeignKey { table, column, references } => out.push(add_fk(table, column, references)),
        Op::DropForeignKey { table, name } => {
            out.push(format!("ALTER TABLE {} DROP FOREIGN KEY {};", q(table), q(&fk_name(table, name))));
        }

        // Relationships are query-level sugar over foreign keys; no DDL.
        Op::AddRelationship { .. } | Op::DropRelationship { .. } => {}

        Op::CreateIndex { table, index } => {
            if let Some(t) = cx.schemas.new.table(table) {
                for c in &index.columns {
                    if let Some(col) = t.column(c)
                        && !indexable(&col.ty)
                    {
                        return Err(fail(index_refusal(table, c, &col.ty)));
                    }
                }
            }
            let cols: Vec<_> = index.columns.iter().map(|c| q(c)).collect();
            out.push(format!("CREATE INDEX {} ON {} ({});", q(&index.name), q(table), cols.join(", ")));
        }
        Op::DropIndex { table, name } => out.push(format!("DROP INDEX {} ON {};", q(name), q(table))),

        Op::AddConstraint { table, constraint } => {
            out.push(format!(
                "ALTER TABLE {} ADD CONSTRAINT {} CHECK ({});",
                q(table), q(&constraint.name), expr(&constraint.expr).map_err(fail)?
            ));
        }
        Op::DropConstraint { table, name } => out.push(format!("ALTER TABLE {} DROP CHECK {};", q(table), q(name))),

        Op::RenameTable { from, to, columns } => {
            out.push(format!("RENAME TABLE {} TO {};", q(from), q(to)));
            // constraint names are derived from table and column names; keep them in step
            for c in columns {
                if c.unique && !c.primary_key {
                    out.push(format!(
                        "ALTER TABLE {} RENAME INDEX {} TO {};",
                        q(to), q(&unique_name(from, &c.name)), q(&unique_name(to, &c.name))
                    ));
                }
                if let Some(r) = &c.references {
                    out.push(format!("ALTER TABLE {} DROP FOREIGN KEY {};", q(to), q(&fk_name(from, &c.name))));
                    out.push(add_fk(to, &c.name, r));
                }
            }
        }
        Op::RenameColumn { table, from, to, column } => {
            out.push(format!("ALTER TABLE {} RENAME COLUMN {} TO {};", q(table), q(from), q(to)));
            if column.unique && !column.primary_key {
                out.push(format!(
                    "ALTER TABLE {} RENAME INDEX {} TO {};",
                    q(table), q(&unique_name(table, from)), q(&unique_name(table, to))
                ));
            }
            if let Some(r) = &column.references {
                out.push(format!("ALTER TABLE {} DROP FOREIGN KEY {};", q(table), q(&fk_name(table, from))));
                out.push(add_fk(table, to, r));
            }
        }

        Op::DataUpdate { table, set, filter } => {
            let mut assigns = Vec::new();
            for a in set {
                assigns.push(format!("{} = {}", q(&a.column), expr(&a.value).map_err(fail)?));
            }
            let mut s = format!("UPDATE {} SET {}", q(table), assigns.join(", "));
            if let Some(f) = filter {
                s.push_str(&format!(" WHERE {}", expr(f).map_err(fail)?));
            }
            out.push(s + ";");
        }
        Op::Backfill { table, column, value } => {
            out.push(format!(
                "UPDATE {} SET {c} = {} WHERE {c} IS NULL;",
                q(table), expr(value).map_err(fail)?, c = q(column)
            ));
            // the column's final definition, which is NOT NULL
            let def = cx
                .schemas
                .new
                .table(table)
                .and_then(|t| t.column(column))
                .ok_or_else(|| fail(format!("column `{table}.{column}` is not in the new schema")))?;
            out.push(cx.modify(table, def).map_err(fail)?);
        }
        Op::RawSql { dialect, sql } => {
            if dialect.as_deref().is_none_or(|d| d == "mysql") {
                out.push(raw_sql(sql));
            }
        }
    }
    Ok(())
}

/// MySQL commits DDL as it goes, so there is nothing to wrap in a transaction: every statement is a batch of its
/// own, which a runner can record one at a time.
pub(crate) fn lower_batches(plan: &MigrationPlan, schemas: &Schemas) -> Result<Vec<Batch>, LowerError> {
    let cx = Cx { schemas };
    let mut batches = Vec::new();
    for op in &plan.ops {
        let mut out = Vec::new();
        lower_op(&cx, op, &mut out)?;
        batches.extend(out.into_iter().map(|s| Batch { transactional: false, statements: vec![s] }));
    }
    Ok(batches)
}
