/* Generated by certo-ffi — do not edit */
#ifndef ADD_H
#define ADD_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* Certo runtime types */
typedef struct { int64_t value; int8_t scale; } certo_decimal_t;
typedef struct { uint8_t bytes[16]; }           certo_uuid_t;
typedef struct { bool has_value; void* value; } certo_option_t;
typedef struct { void* value; }                 certo_tuple_t;
typedef void (*certo_fn_t)(void);
/* pub fn add(a: Int, b: Int): Int */
int64_t certo_add(int64_t a, int64_t b);

#endif /* ADD_H */
