//! Live PostgreSQL test for serial, identity columns and sequences: written in
//! SDL, lowered, applied, read back with no drift, exercised, and evolved with
//! rows in the table.
//!
//! Skipped unless `CERTO_TEST_PG_URL` is set. WARNING: it DROPS and recreates
//! the `public` schema of that database; use a throwaway database only.

use certo_runner::drift;
use certo_runner::migration::create;
use certo_runner::{apply, ApplyOptions, Executor, PgExecutor, Project};
use certo_sdl::Generation;
use postgres::{Client, NoTls};

fn url() -> Option<String> { std::env::var("CERTO_TEST_PG_URL").ok().filter(|u| !u.is_empty()) }

fn texts(d: &drift::Drift) -> Vec<String> {
    d.items.iter().map(|i| format!("{:?}: {}", i.kind, i.text)).collect()
}

struct Env {
    project: Project,
    db: PgExecutor,
    raw: Client,
    _dir: tempfile::TempDir,
}

impl Env {
    /// Write `schema`, create a migration (allowing destructive ones), apply it, require no drift.
    fn migrate(&mut self, name: &str, schema: &str, mdl: Option<(&str, &str)>) {
        std::fs::write(self.project.schema_path(), schema).unwrap();
        create(&self.project, name, mdl, true).unwrap_or_else(|e| panic!("{name}: {e}"));
        apply(&self.project, &mut self.db, &ApplyOptions::default()).unwrap_or_else(|e| panic!("{name}: {e}"));
        let d = drift::check(&self.project, &mut self.db).unwrap();
        assert!(d.in_sync(), "{name}: the database must match the schema, got:\n{}", texts(&d).join("\n"));
    }

    fn ints(&mut self, sql: &str) -> Vec<i64> {
        self.raw.query(sql, &[]).unwrap().iter().map(|r| r.get::<_, i64>(0)).collect()
    }

    fn fails(&self, sql: &str, needle: &str) {
        let mut c = Client::connect(&url().unwrap(), NoTls).unwrap();
        let e = c.batch_execute(sql).expect_err(sql);
        let msg = e.as_db_error().map(|d| d.message().to_string()).unwrap_or_default();
        assert!(msg.contains(needle), "`{sql}` should fail with `{needle}`, got: {msg}");
    }
}

fn env() -> Option<Env> {
    let url = url()?;
    let mut raw = Client::connect(&url, NoTls).expect("connect");
    raw.batch_execute("DROP SCHEMA public CASCADE; CREATE SCHEMA public;").unwrap();
    let dir = tempfile::tempdir().unwrap();
    let project = Project::init(dir.path(), "postgres").unwrap();
    let db = PgExecutor::connect(&url).unwrap();
    Some(Env { project, db, raw, _dir: dir })
}

const V1: &str = r#"
sequence order_seq start 1000 increment 5

table orders {
    id: serial primary key
    ref: bigint default nextval(order_seq)
    note: text
}

table logs {
    id: bigserial primary key
    small: smallserial
    a: bigint generated always
    b: int generated by default
    msg: text
}
"#;

#[test]
fn serial_identity_and_sequences_lower_apply_and_read_back_exactly() {
    let Some(mut e) = env() else {
        eprintln!("CERTO_TEST_PG_URL not set; skipping live PostgreSQL test");
        return;
    };
    e.migrate("init", V1, None);

    // the read-back schema has exactly the generations we wrote
    let live = e.db.introspect().unwrap();
    assert!(live.notes.is_empty(), "{:?}", live.notes);
    let orders = live.ir.table("orders").unwrap();
    assert_eq!(orders.column("id").unwrap().generated, Some(Generation::Serial));
    assert!(orders.column("id").unwrap().default.is_none(), "serial's nextval default is implied, not reported");
    let logs = live.ir.table("logs").unwrap();
    assert_eq!(logs.column("id").unwrap().generated, Some(Generation::Serial));
    assert_eq!(logs.column("small").unwrap().generated, Some(Generation::Serial));
    assert_eq!(logs.column("a").unwrap().generated, Some(Generation::Always));
    assert_eq!(logs.column("b").unwrap().generated, Some(Generation::ByDefault));
    assert_eq!(live.ir.sequences.len(), 1, "only the standalone sequence, not the ones serial owns");
    let s = &live.ir.sequences[0];
    assert_eq!((s.name.as_str(), s.start, s.increment), ("order_seq", 1000, 5));

    // ---- behaviour ---------------------------------------------------------------
    e.raw.batch_execute("INSERT INTO orders (note) VALUES ('x'), ('y'), ('z')").unwrap();
    assert_eq!(e.ints("SELECT id::bigint FROM orders ORDER BY id"), [1, 2, 3], "serial counts up");
    assert_eq!(e.ints("SELECT ref FROM orders ORDER BY id"), [1000, 1005, 1010], "nextval(order_seq) steps by 5 from 1000");
    e.raw.batch_execute("INSERT INTO logs (msg) VALUES ('m1'), ('m2')").unwrap();
    assert_eq!(e.ints("SELECT a FROM logs ORDER BY id"), [1, 2], "identity always generates");
    assert_eq!(e.ints("SELECT small::bigint FROM logs ORDER BY id"), [1, 2]);
    e.fails("INSERT INTO logs (a, msg) VALUES (99, 'm')", "non-DEFAULT value");
    e.raw.batch_execute("INSERT INTO logs (b, msg) VALUES (500, 'override')").unwrap(); // BY DEFAULT allows it
    assert_eq!(e.ints("SELECT b::bigint FROM logs WHERE msg = 'override'"), [500]);

    // ---- a sequence change and dropping a sequence -------------------------------------
    e.migrate("faster", &V1.replace("increment 5", "increment 10 cache 20"), None);
    e.raw.batch_execute("INSERT INTO orders (note) VALUES ('w')").unwrap();
    let last = e.ints("SELECT ref FROM orders ORDER BY id DESC LIMIT 1")[0];
    assert!(last >= 1015, "the counter carries on past the old values, got {last}");
    e.migrate(
        "drop the sequence",
        &V1.replace("sequence order_seq start 1000 increment 5\n", "").replace("ref: bigint default nextval(order_seq)", "ref: bigint"),
        None,
    );
    assert_eq!(e.ints("SELECT count(*) FROM pg_class WHERE relname = 'order_seq' AND relnamespace = 'public'::regnamespace"), [0]);
    assert_eq!(e.ints("SELECT count(*) FROM orders"), [4], "the rows survived");
}

#[test]
fn a_column_can_move_through_every_generation_with_rows_in_place() {
    let Some(mut e) = env() else {
        eprintln!("CERTO_TEST_PG_URL not set; skipping live PostgreSQL test");
        return;
    };
    let schema = |n: &str| format!("table items {{\n    id: int primary key\n    n: {n}\n}}\n");
    e.migrate("plain", &schema("int not null"), None);
    e.raw.batch_execute("INSERT INTO items (id, n) VALUES (1, 10), (2, 20), (3, 30)").unwrap();

    // none -> serial: an owned sequence is built and caught up to the existing rows
    e.migrate("to serial", &schema("serial"), None);
    e.raw.batch_execute("INSERT INTO items (id) VALUES (4)").unwrap();
    assert_eq!(e.ints("SELECT n::bigint FROM items WHERE id = 4"), [31], "next value follows the largest existing one");

    // serial -> identity always: the serial sequence goes, an identity takes over, caught up again
    e.migrate("to identity", &schema("int generated always"), None);
    assert_eq!(e.ints("SELECT count(*) FROM pg_class WHERE relkind = 'S' AND relnamespace = 'public'::regnamespace"), [1], "exactly one sequence left (the identity's)");
    e.raw.batch_execute("INSERT INTO items (id) VALUES (5)").unwrap();
    assert_eq!(e.ints("SELECT n::bigint FROM items WHERE id = 5"), [32]);
    e.fails("INSERT INTO items (id, n) VALUES (6, 1)", "non-DEFAULT value");

    // identity always -> by default: overriding is now allowed
    e.migrate("by default", &schema("int generated by default"), None);
    e.raw.batch_execute("INSERT INTO items (id, n) VALUES (6, 1000)").unwrap();

    // identity -> serial, then serial -> none
    e.migrate("back to serial", &schema("serial"), None);
    e.raw.batch_execute("INSERT INTO items (id) VALUES (7)").unwrap();
    assert!(e.ints("SELECT n::bigint FROM items WHERE id = 7")[0] > 1000, "caught up past the override");
    e.migrate("to plain", &schema("int not null"), None);
    assert_eq!(e.ints("SELECT count(*) FROM pg_class WHERE relkind = 'S' AND relnamespace = 'public'::regnamespace"), [0], "no sequence left behind");
    e.fails("INSERT INTO items (id) VALUES (8)", "null value");
    assert_eq!(e.ints("SELECT count(*) FROM items"), [7], "every row survived every change");
}

#[test]
fn a_renamed_serial_column_can_still_be_taken_off_serial() {
    let Some(mut e) = env() else {
        eprintln!("CERTO_TEST_PG_URL not set; skipping live PostgreSQL test");
        return;
    };
    let schema = |col: &str, ty: &str| format!("table t {{\n    {col}: {ty} primary key\n    v: text\n}}\n");
    e.migrate("init", &schema("id", "serial"), None);
    e.raw.batch_execute("INSERT INTO t (v) VALUES ('a'), ('b')").unwrap();
    // renaming a column does not rename the sequence PostgreSQL made for it
    e.migrate("rename", &schema("key", "serial"), Some(("rename.mdl", "rename column t.id -> key")));
    assert_eq!(e.ints("SELECT count(*) FROM pg_class WHERE relname = 't_id_seq' AND relnamespace = 'public'::regnamespace"), [1], "the sequence keeps its old name");
    e.raw.batch_execute("INSERT INTO t (v) VALUES ('c')").unwrap();
    assert_eq!(e.ints("SELECT key::bigint FROM t ORDER BY key"), [1, 2, 3]);
    // dropping serial must find that sequence through its ownership, not its derived name
    e.migrate("plain", &schema("key", "int"), None);
    assert_eq!(e.ints("SELECT count(*) FROM pg_class WHERE relkind = 'S' AND relnamespace = 'public'::regnamespace"), [0], "the renamed column's sequence was dropped");
}

#[test]
fn hand_edits_of_generations_and_sequences_are_detected_and_repairable() {
    let Some(mut e) = env() else {
        eprintln!("CERTO_TEST_PG_URL not set; skipping live PostgreSQL test");
        return;
    };
    e.migrate("init", V1, None);

    let cases: &[(&str, &str, &str)] = &[
        ("identity dropped", "ALTER TABLE logs ALTER COLUMN a DROP IDENTITY", "column logs.a: auto-generation"),
        ("identity flipped", "ALTER TABLE logs ALTER COLUMN b SET GENERATED ALWAYS", "column logs.b: auto-generation"),
        ("sequence changed", "ALTER SEQUENCE order_seq INCREMENT BY 7", "sequence order_seq"),
        ("sequence dropped by hand", "ALTER TABLE orders ALTER COLUMN ref DROP DEFAULT; DROP SEQUENCE order_seq", "sequence order_seq"),
        ("stray sequence", "CREATE SEQUENCE stray_seq", "sequence stray_seq"),
    ];
    for (what, sql, needle) in cases {
        e.raw.batch_execute(sql).unwrap_or_else(|err| panic!("{what}: {err}"));
        let d = drift::check(&e.project, &mut e.db).unwrap();
        assert!(texts(&d).iter().any(|t| t.contains(needle)), "{what}: expected `{needle}` in:\n{}", texts(&d).join("\n"));
        let script = certo_sql::render(&d.plan, certo_sql::Dialect::Postgres)
            .unwrap_or_else(|err| panic!("{what}: repair not lowerable: {err}"));
        e.raw.batch_execute(&script).unwrap_or_else(|err| panic!("{what}: repair failed: {err}\n{script}"));
        let after = drift::check(&e.project, &mut e.db).unwrap();
        assert!(after.in_sync(), "{what}: still drifting after repair:\n{}\n{script}", texts(&after).join("\n"));
    }
}
