[package]
name    = "certo-lsp"
version = "0.1.0"
edition = "2024"
license = "MIT"

[[bin]]
name = "certo-lsp"
path = "src/main.rs"

[dependencies]
certo-ast     = { path = "../ast" }
certo-parser  = { path = "../parser" }
certo-resolve = { path = "../resolve" }
certo-typeck  = { path = "../typeck" }
certo-stdlib  = { path = "../stdlib" }
lsp-server    = "0.7"
lsp-types     = "0.95"
serde_json    = "1"
serde         = { version = "1", features = ["derive"] }
