//! Syntactic AST for SDL. No name resolution happens here.

use certo_ast::span::Span;

#[derive(Debug, Clone, PartialEq)]
pub struct SdlFile {
    pub decls: Vec<Decl>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Decl {
    Sequence(SequenceDecl),
    Table(TableDecl),
    Enum(EnumDecl),
    Type(TypeDecl),
    Index(IndexDecl),
    Constraint(ConstraintDecl),
}

#[derive(Debug, Clone, PartialEq)]
pub struct Ident {
    pub name: String,
    pub span: Span,
}

/// A type reference: a name and optional numeric parameters, e.g. `varchar(255)`.
#[derive(Debug, Clone, PartialEq)]
pub struct TypeRef {
    pub name: Ident,
    pub args: Vec<u32>,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub struct TableDecl {
    pub name: Ident,
    pub members: Vec<Member>,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Member {
    Column(ColumnDecl),
    Rel(RelDecl),
}

#[derive(Debug, Clone, PartialEq)]
pub struct ColumnDecl {
    pub name: Ident,
    pub ty: TypeRef,
    pub mods: Vec<ColumnMod>,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub enum ColumnMod {
    PrimaryKey(Span),
    Unique(Span),
    NotNull(Span),
    Null(Span),
    Default(Expr),
    /// `generated always` / `generated by default` (identity column)
    Generated { kind: Generation, span: Span },
    /// `references Table [(column)] [on delete <action>] [on update <action>]`
    References {
        table: Ident,
        column: Option<Ident>,
        on_delete: Option<ReferentialAction>,
        on_update: Option<ReferentialAction>,
        span: Span,
    },
}

/// How a column's value is generated. `Serial` is the sequence-backed default
/// of the `serial` types; `Always` / `ByDefault` are SQL-standard identity columns.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Generation {
    Serial,
    Always,
    ByDefault,
}

/// `sequence name [start N] [increment N] [min N] [max N] [cache N] [cycle]`
#[derive(Debug, Clone, PartialEq)]
pub struct SequenceDecl {
    pub name: Ident,
    pub options: Vec<SeqOption>,
    pub span: Span,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SeqOptKind {
    Start,
    Increment,
    Min,
    Max,
    Cache,
    Cycle,
}

#[derive(Debug, Clone, PartialEq)]
pub struct SeqOption {
    pub kind: SeqOptKind,
    /// `None` for `cycle`.
    pub value: Option<i64>,
    pub span: Span,
}

/// What happens to a referencing row when its referenced row is deleted or
/// updated. `NoAction` is the default when a clause is omitted.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ReferentialAction {
    #[default]
    NoAction,
    Restrict,
    Cascade,
    SetNull,
}

#[derive(Debug, Clone, PartialEq)]
pub struct RelDecl {
    pub name: Ident,
    pub target: Ident,
    pub cardinality: Cardinality,
    pub span: Span,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Cardinality {
    One,
    Optional,
    Many,
}

#[derive(Debug, Clone, PartialEq)]
pub struct EnumDecl {
    pub name: Ident,
    pub variants: Vec<Ident>,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub struct TypeDecl {
    pub name: Ident,
    pub fields: Vec<FieldDecl>,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub struct FieldDecl {
    pub name: Ident,
    pub ty: TypeRef,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub struct IndexDecl {
    pub name: Ident,
    pub table: Ident,
    pub columns: Vec<Ident>,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub struct ConstraintDecl {
    pub name: Ident,
    pub table: Ident,
    pub expr: Expr,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Expr {
    Literal(Literal, Span),
    Ident(Ident),
    Call { func: Ident, args: Vec<Expr>, span: Span },
    Binary { op: BinaryOp, lhs: Box<Expr>, rhs: Box<Expr>, span: Span },
    Paren(Box<Expr>, Span),
    /// `not e`
    Not(Box<Expr>, Span),
    /// `e is null` / `e is not null`
    IsNull { expr: Box<Expr>, negated: bool, span: Span },
    /// `e in (a, b)` / `e not in (a, b)`
    In { expr: Box<Expr>, list: Vec<Expr>, negated: bool, span: Span },
}

impl Expr {
    pub fn span(&self) -> Span {
        match self {
            Expr::Literal(_, s) | Expr::Paren(_, s) | Expr::Not(_, s) => *s,
            Expr::Ident(i) => i.span,
            Expr::Call { span, .. }
            | Expr::Binary { span, .. }
            | Expr::IsNull { span, .. }
            | Expr::In { span, .. } => *span,
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum Literal {
    String(String),
    Number(i64),
    /// Decimal text as written, sign included (`-1.5`).
    Decimal(String),
    Bool(bool),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum BinaryOp {
    Eq, Ne, Lt, Le, Gt, Ge,
    Add, Sub, Mul, Div,
    And, Or,
}

impl BinaryOp {
    /// Binding power; higher binds tighter. All operators are left-associative.
    /// `not` sits at 3 (between `and` and comparison); `is null` and `in` at 4.
    pub fn precedence(self) -> u8 {
        use BinaryOp::*;
        match self {
            Or => 1,
            And => 2,
            Eq | Ne | Lt | Le | Gt | Ge => 4,
            Add | Sub => 5,
            Mul | Div => 6,
        }
    }
}
