//! SchemaIR -> SDL source. The inverse of `compile`: compiling the printed
//! text gives back the same IR (relationships included), so a schema that
//! exists only as an IR (for example one introspected from a live database)
//! can become a `schema.sdl` file.
//!
//! Output is canonical: declarations in IR order (already sorted by name),
//! modifiers in a fixed order, minimal parentheses. Printing fails only for
//! `ExprIR::Raw`, which is server text SDL cannot express.

use crate::ast::{BinaryOp, Cardinality, Generation, ReferentialAction};
use crate::expr::describe;
use crate::ir::*;
use std::fmt::Write;

/// Print `ir` as SDL source text.
pub fn to_sdl(ir: &SchemaIR) -> Result<String, String> {
    let mut blocks: Vec<String> = Vec::new();

    for e in &ir.enums {
        blocks.push(format!("enum {} {{ {} }}", e.name, e.variants.join(", ")));
    }
    for s in &ir.sequences {
        blocks.push(sequence(s));
    }
    for t in &ir.types {
        let fields: Vec<String> = t.fields.iter().map(|f| format!("{}: {}", f.name, ty(&f.ty))).collect();
        let mut s = format!("type {} {{\n", t.name);
        for f in fields {
            let _ = writeln!(s, "    {f}");
        }
        s.push('}');
        blocks.push(s);
    }
    for t in &ir.tables {
        let mut s = format!("table {} {{\n", t.name);
        for c in &t.columns {
            let _ = writeln!(s, "    {}", column(ir, c)?);
        }
        for r in &t.relationships {
            let card = match r.cardinality {
                Cardinality::One => "one",
                Cardinality::Optional => "optional",
                Cardinality::Many => "many",
            };
            let _ = writeln!(s, "    {}: {} -> {card}", r.name, r.target);
        }
        s.push('}');
        blocks.push(s);
    }
    let mut trailing: Vec<String> = Vec::new();
    for t in &ir.tables {
        for i in &t.indexes {
            trailing.push(format!("index {} on {} ({})", i.name, t.name, i.columns.join(", ")));
        }
        for k in &t.constraints {
            trailing.push(format!("constraint {} on {} using {}", k.name, t.name, expr(&k.expr, 0, false)?));
        }
    }
    for v in &ir.views {
        let mut line = format!("view {} on {} ({})", v.name, v.from, v.columns.join(", "));
        if let Some(f) = &v.filter {
            line.push_str(&format!(" where {}", expr(f, 0, false)?));
        }
        trailing.push(line);
    }
    if !trailing.is_empty() {
        blocks.push(trailing.join("\n"));
    }

    if blocks.is_empty() {
        return Ok(String::new());
    }
    Ok(blocks.join("\n\n") + "\n")
}

fn ty(t: &TypeIR) -> String { describe(t) }

fn sequence(s: &SequenceIR) -> String {
    let (dmin, dmax) = if s.increment > 0 { (1, i64::MAX) } else { (i64::MIN, -1) };
    let dstart = if s.increment > 0 { s.min } else { s.max };
    let mut out = format!("sequence {}", s.name);
    if s.start != dstart { let _ = write!(out, " start {}", s.start); }
    if s.increment != 1 { let _ = write!(out, " increment {}", s.increment); }
    if s.min != dmin { let _ = write!(out, " min {}", s.min); }
    if s.max != dmax { let _ = write!(out, " max {}", s.max); }
    if s.cache != 1 { let _ = write!(out, " cache {}", s.cache); }
    if s.cycle { out.push_str(" cycle"); }
    out
}

fn column(ir: &SchemaIR, c: &ColumnIR) -> Result<String, String> {
    let type_text = match (c.generated, &c.ty) {
        (Some(Generation::Serial), TypeIR::Builtin(Builtin::SmallInt)) => "smallserial".to_string(),
        (Some(Generation::Serial), TypeIR::Builtin(Builtin::BigInt)) => "bigserial".to_string(),
        (Some(Generation::Serial), _) => "serial".to_string(),
        _ => ty(&c.ty),
    };
    let mut s = format!("{}: {type_text}", c.name);
    if c.primary_key {
        s.push_str(" primary key");
    } else if !c.nullable && c.generated.is_none() {
        s.push_str(" not null");
    }
    if c.unique {
        s.push_str(" unique");
    }
    match c.generated {
        Some(Generation::Always) => s.push_str(" generated always"),
        Some(Generation::ByDefault) => s.push_str(" generated by default"),
        _ => {}
    }
    if let Some(d) = &c.default {
        s.push_str(" default ");
        s.push_str(&expr(d, 0, false)?);
    }
    if let Some(fk) = &c.references {
        let sole_pk = ir.table(&fk.table).is_some_and(|t| {
            let pks: Vec<_> = t.columns.iter().filter(|c| c.primary_key).collect();
            pks.len() == 1 && pks[0].name == fk.column
        });
        let _ = write!(s, " references {}", fk.table);
        if !sole_pk {
            let _ = write!(s, "({})", fk.column);
        }
        for (kw, a) in [("delete", fk.on_delete), ("update", fk.on_update)] {
            let word = match a {
                ReferentialAction::NoAction => continue,
                ReferentialAction::Restrict => "restrict",
                ReferentialAction::Cascade => "cascade",
                ReferentialAction::SetNull => "set null",
            };
            let _ = write!(s, " on {kw} {word}");
        }
    }
    Ok(s)
}

fn op_str(op: BinaryOp) -> &'static str {
    match op {
        BinaryOp::Eq => "==",
        BinaryOp::Ne => "!=",
        BinaryOp::Lt => "<",
        BinaryOp::Le => "<=",
        BinaryOp::Gt => ">",
        BinaryOp::Ge => ">=",
        BinaryOp::Add => "+",
        BinaryOp::Sub => "-",
        BinaryOp::Mul => "*",
        BinaryOp::Div => "/",
        BinaryOp::And => "and",
        BinaryOp::Or => "or",
    }
}

fn string_lit(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// All operators are left-associative, so a right operand of equal precedence
/// needs parentheses; a lower-precedence child always does.
fn expr(e: &ExprIR, parent_prec: u8, right: bool) -> Result<String, String> {
    Ok(match e {
        ExprIR::Number { value } => value.to_string(),
        ExprIR::Decimal { value } => value.clone(),
        ExprIR::Not { expr: inner } => {
            let s = format!("not {}", expr(inner, 3, false)?);
            if 3 < parent_prec { format!("({s})") } else { s }
        }
        ExprIR::IsNull { expr: inner, negated } => {
            let s = format!("{} is {}null", expr(inner, 5, false)?, if *negated { "not " } else { "" });
            if 4 < parent_prec || (4 == parent_prec && right) { format!("({s})") } else { s }
        }
        ExprIR::In { expr: inner, list, negated } => {
            let items: Result<Vec<_>, _> = list.iter().map(|i| expr(i, 0, false)).collect();
            let s = format!("{} {}in ({})", expr(inner, 5, false)?, if *negated { "not " } else { "" }, items?.join(", "));
            if 4 < parent_prec || (4 == parent_prec && right) { format!("({s})") } else { s }
        }
        ExprIR::String { value } => string_lit(value),
        ExprIR::Bool { value } => value.to_string(),
        ExprIR::Column { name } => name.clone(),
        ExprIR::NextVal { sequence } => format!("nextval({sequence})"),
        ExprIR::EnumVariant { variant, .. } => variant.clone(),
        ExprIR::Call { func, args } => {
            let a: Result<Vec<_>, _> = args.iter().map(|a| expr(a, 0, false)).collect();
            format!("{func}({})", a?.join(", "))
        }
        ExprIR::Binary { op, lhs, rhs } => {
            let p = op.precedence();
            let s = format!("{} {} {}", expr(lhs, p, false)?, op_str(*op), expr(rhs, p, true)?);
            if p < parent_prec || (p == parent_prec && right) { format!("({s})") } else { s }
        }
        ExprIR::Raw { .. } => return Err("a raw SQL expression cannot be written as SDL".into()),
    })
}

#[cfg(test)]
mod tests {
    use crate::*;

    fn roundtrip(src: &str) -> String {
        let (ir, d) = compile(src);
        let ir = ir.unwrap_or_else(|| panic!("source failed: {d:?}"));
        let printed = to_sdl(&ir).unwrap();
        let (again, d2) = compile(&printed);
        let again = again.unwrap_or_else(|| panic!("printed SDL failed to compile: {d2:?}\n{printed}"));
        assert_eq!(again, ir, "round trip changed the IR:\n{printed}");
        assert_eq!(to_sdl(&again).unwrap(), printed, "printing is not idempotent");
        printed
    }

    #[test]
    fn empty_schema() {
        assert_eq!(to_sdl(&SchemaIR::empty()).unwrap(), "");
        roundtrip("");
    }

    #[test]
    fn a_rich_schema_round_trips() {
        let printed = roundtrip(
            r#"
            enum Role { admin, user, guest }
            type Address { street: text  city: text }
            table users {
                id: uuid primary key default gen_uuid()
                email: text not null unique
                role: Role default user
                age: int default 18
                score: float default 1
                balance: decimal
                visits: bigint default 0
                active: bool not null default true
                meta: json
                avatar: bytes
                born: date
                created: timestamp not null default now()
                home: Address
                nick: text default "anon"
                code: text default "it's \"q\" \\ x"
                posts: posts -> many
            }
            table posts {
                id: uuid primary key
                author_id: uuid not null references users on delete cascade on update restrict
                editor_id: uuid references users on delete set null
                title: text not null default "untitled"
                parent_id: uuid references posts
            }
            table tags { a: int primary key  b: int primary key  label: text unique  ref_l: text references tags(label) }
            index users_email_role on users (email, role)
            constraint adult on users using age >= 18 and role != admin
            constraint sane on users using score >= 0 or is_null(score)
            "#,
        );
        assert!(printed.contains("author_id: uuid not null references users on delete cascade on update restrict"), "{printed}");
        assert!(printed.contains("editor_id: uuid references users on delete set null"), "{printed}");
        assert!(printed.contains("posts: posts -> many"), "{printed}");
        assert!(printed.contains("role: Role default user"), "{printed}");
    }

    #[test]
    fn explicit_reference_column_only_when_not_the_sole_primary_key() {
        let printed = roundtrip(
            "table u { id: int primary key  k: int unique } table t { id: int primary key  a: int references u  b: int references u(k) }",
        );
        assert!(printed.contains("a: int references u\n"), "{printed}");
        assert!(printed.contains("b: int references u(k)\n"), "{printed}");
    }

    #[test]
    fn expression_parentheses_are_minimal_and_correct() {
        for (src, expected) in [
            ("a or b and c", "a or b and c"),
            ("(a or b) and c", "(a or b) and c"),
            ("a - b - c", "a - b - c"),
            ("a - (b - c)", "a - (b - c)"),
            ("(a + b) * c", "(a + b) * c"),
            ("a + b * c", "a + b * c"),
            ("a / (b * c)", "a / (b * c)"),
            ("(a == b) == c", "a == b == c"),
            ("a == (b == c)", "a == (b == c)"),
            ("((a))", "a"),
            // the widened operators
            ("not a == b", "not a == b"),
            ("(not a) == b", "(not a) == b"),
            ("not (a or b)", "not (a or b)"),
            ("not a or b", "not a or b"),
            ("not a and b", "not a and b"),
            ("a is null or b", "a is null or b"),
            ("a == (b is null)", "a == (b is null)"),
            ("(a == b) is null", "(a == b) is null"),
            ("a + b is not null", "a + b is not null"),
            ("a in (b, c) and d", "a in (b, c) and d"),
            ("a == (b in (c))", "a == (b in (c))"),
            ("not a not in (b)", "not a not in (b)"),
            ("a - -1", "a - -1"),
            ("a - (-1)", "a - -1"),
            ("-2 * a", "-2 * a"),
            ("a in (b - c, -1.5)", "a in (b - c, -1.5)"),
        ] {
            let schema = format!("table t {{ id: int primary key  a: bool  b: bool  c: bool }} constraint k on t using {src}");
            // typing may reject some of these (int vs bool); test the expression layer directly
            let (file, d) = parse(&schema);
            assert!(d.is_empty(), "{src}: {d:?}");
            let Decl::Constraint(c) = &file.decls[1] else { panic!() };
            let ir = lower_for_test(&c.expr);
            assert_eq!(super::expr(&ir, 0, false).unwrap(), expected, "{src}");
            // and the printed form parses back to the same tree
            let (file2, d2) = parse(&format!("constraint k on t using {expected}"));
            assert!(d2.is_empty());
            let Decl::Constraint(c2) = &file2.decls[0] else { panic!() };
            assert_eq!(lower_for_test(&c2.expr), ir, "{src}");
        }
    }

    /// AST -> ExprIR without type checking (columns become `Column`).
    fn lower_for_test(e: &Expr) -> ExprIR {
        match e {
            Expr::Literal(Literal::Number(n), _) => ExprIR::Number { value: *n },
            Expr::Literal(Literal::Decimal(d), _) => ExprIR::Decimal { value: d.clone() },
            Expr::Not(e, _) => ExprIR::Not { expr: Box::new(lower_for_test(e)) },
            Expr::IsNull { expr, negated, .. } => ExprIR::IsNull { expr: Box::new(lower_for_test(expr)), negated: *negated },
            Expr::In { expr, list, negated, .. } => ExprIR::In {
                expr: Box::new(lower_for_test(expr)),
                list: list.iter().map(lower_for_test).collect(),
                negated: *negated,
            },
            Expr::Literal(Literal::String(s), _) => ExprIR::String { value: s.clone() },
            Expr::Literal(Literal::Bool(b), _) => ExprIR::Bool { value: *b },
            Expr::Ident(i) => ExprIR::Column { name: i.name.clone() },
            Expr::Call { func, args, .. } => ExprIR::Call { func: func.name.clone(), args: args.iter().map(lower_for_test).collect() },
            Expr::Binary { op, lhs, rhs, .. } => ExprIR::Binary { op: *op, lhs: Box::new(lower_for_test(lhs)), rhs: Box::new(lower_for_test(rhs)) },
            Expr::Paren(inner, _) => lower_for_test(inner),
        }
    }

    #[test]
    fn strings_with_special_characters_survive() {
        let printed = roundtrip("table t { id: int primary key  s: text default \"a\\\"b\\\\c\\nd\\te \u{e9}\u{1F600}\" }");
        assert!(printed.contains("\\\""), "{printed}");
    }

    #[test]
    fn raw_expressions_cannot_be_printed() {
        let mut ir = SchemaIR::empty();
        let (base, _) = compile("table t { id: int primary key  x: int }");
        ir.tables = base.unwrap().tables;
        ir.tables[0].columns[1].default = Some(ExprIR::Raw { sql: "nextval('s')".into() });
        assert!(to_sdl(&ir).unwrap_err().contains("raw SQL"));
    }
}
