// A typed view of the schema IR (what `CertoSdl.Compile` produces), for hosts that list or inspect a schema.
// The IR itself stays available as JSON; expressions (defaults, CHECK bodies) are kept as raw JSON.

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Certo.Models
{
    public enum ReferentialAction { NoAction, Restrict, Cascade, SetNull }

    /// <summary>How a column's value is generated.</summary>
    public enum Generation { Serial, Always, ByDefault }

    public sealed class SchemaReference
    {
        [JsonPropertyName("table")] public string Table { get; init; } = "";
        [JsonPropertyName("column")] public string Column { get; init; } = "";
        [JsonPropertyName("on_delete"), JsonConverter(typeof(LowerEnumConverter<ReferentialAction>))]
        public ReferentialAction OnDelete { get; init; }
        [JsonPropertyName("on_update"), JsonConverter(typeof(LowerEnumConverter<ReferentialAction>))]
        public ReferentialAction OnUpdate { get; init; }
    }

    public sealed class SchemaColumn
    {
        [JsonPropertyName("name")] public string Name { get; init; } = "";
        [JsonPropertyName("type")] public SchemaType Type { get; init; } = new();
        [JsonPropertyName("primary_key")] public bool PrimaryKey { get; init; }
        [JsonPropertyName("unique")] public bool Unique { get; init; }
        [JsonPropertyName("nullable")] public bool Nullable { get; init; }
        /// <summary>The default expression as JSON; null when there is none.</summary>
        [JsonPropertyName("default")] public JsonElement? Default { get; init; }
        [JsonPropertyName("references")] public SchemaReference? References { get; init; }
        [JsonPropertyName("generated"), JsonConverter(typeof(NullableLowerEnumConverter<Generation>))]
        public Generation? Generated { get; init; }

        /// <summary>A short description in SDL's words: <c>id serial primary key</c>, <c>email varchar(100) not null unique</c>.</summary>
        public override string ToString()
        {
            var parts = new List<string> { Name };
            parts.Add(Generated == Models.Generation.Serial ? "serial" : Type.ToString());
            if (Generated is Models.Generation.Always) parts.Add("generated always");
            if (Generated is Models.Generation.ByDefault) parts.Add("generated by default");
            if (PrimaryKey) parts.Add("primary key");
            else if (!Nullable) parts.Add("not null");
            if (Unique && !PrimaryKey) parts.Add("unique");
            if (Default is { ValueKind: not JsonValueKind.Null }) parts.Add("default ...");
            if (References is { } r) parts.Add($"references {r.Table}({r.Column})");
            return string.Join(" ", parts);
        }
    }

    public sealed class SchemaIndex
    {
        [JsonPropertyName("name")] public string Name { get; init; } = "";
        [JsonPropertyName("columns")] public List<string> Columns { get; init; } = new();
    }

    public sealed class SchemaConstraint
    {
        [JsonPropertyName("name")] public string Name { get; init; } = "";
        /// <summary>The CHECK expression as JSON.</summary>
        [JsonPropertyName("expr")] public JsonElement Expr { get; init; }
    }

    public sealed class SchemaTable
    {
        [JsonPropertyName("name")] public string Name { get; init; } = "";
        [JsonPropertyName("columns")] public List<SchemaColumn> Columns { get; init; } = new();
        [JsonPropertyName("indexes")] public List<SchemaIndex> Indexes { get; init; } = new();
        [JsonPropertyName("constraints")] public List<SchemaConstraint> Constraints { get; init; } = new();
    }

    public sealed class SchemaEnum
    {
        [JsonPropertyName("name")] public string Name { get; init; } = "";
        [JsonPropertyName("variants")] public List<string> Variants { get; init; } = new();
    }

    public sealed class SchemaField
    {
        [JsonPropertyName("name")] public string Name { get; init; } = "";
        [JsonPropertyName("type")] public SchemaType Type { get; init; } = new();
    }

    /// <summary>A composite type (<c>type Address { ... }</c>).</summary>
    public sealed class SchemaComposite
    {
        [JsonPropertyName("name")] public string Name { get; init; } = "";
        [JsonPropertyName("fields")] public List<SchemaField> Fields { get; init; } = new();
    }

    public sealed class SchemaSequence
    {
        [JsonPropertyName("name")] public string Name { get; init; } = "";
        [JsonPropertyName("start")] public long Start { get; init; }
        [JsonPropertyName("increment")] public long Increment { get; init; }
        [JsonPropertyName("min")] public long Min { get; init; }
        [JsonPropertyName("max")] public long Max { get; init; }
        [JsonPropertyName("cache")] public long Cache { get; init; }
        [JsonPropertyName("cycle")] public bool Cycle { get; init; }
    }

    /// <summary>The compiled schema: the canonical, sorted form every other call works from.</summary>
    public sealed class SchemaIr
    {
        [JsonPropertyName("version")] public int Version { get; init; }
        [JsonPropertyName("tables")] public List<SchemaTable> Tables { get; init; } = new();
        [JsonPropertyName("enums")] public List<SchemaEnum> Enums { get; init; } = new();
        [JsonPropertyName("types")] public List<SchemaComposite> Types { get; init; } = new();
        [JsonPropertyName("sequences")] public List<SchemaSequence> Sequences { get; init; } = new();

        public SchemaTable? Table(string name) => Tables.Find(t => t.Name == name);
    }

    /// <summary>Like <see cref="LowerEnumConverter{T}"/>, for an optional value (JSON null is null).</summary>
    internal sealed class NullableLowerEnumConverter<T> : JsonConverter<T?> where T : struct, System.Enum
    {
        private static readonly LowerEnumConverter<T> Inner = new();

        public override T? Read(ref Utf8JsonReader reader, System.Type typeToConvert, JsonSerializerOptions options) =>
            reader.TokenType == JsonTokenType.Null ? null : Inner.Read(ref reader, typeof(T), options);

        public override void Write(Utf8JsonWriter writer, T? value, JsonSerializerOptions options)
        {
            if (value is { } v) Inner.Write(writer, v, options);
            else writer.WriteNullValue();
        }
    }
}
