//! Generate a C header (`.h`) from the `pub fn` declarations in a Certo module.
//!
//! # Output
//!
//! For a module with:
//!
//! ```certo
//! pub fn add(a: Int, b: Int): Int = a + b
//! pub fn greet(name: Text): Text = name
//! ```
//!
//! `generate_header()` emits:
//!
//! ```c
//! #ifndef MYMODULE_H
//! #define MYMODULE_H
//! #include <stdint.h>
//! #include <stdbool.h>
//! /* ... runtime typedefs ... */
//!
//! /* add — Certo: pub fn add(a: Int, b: Int): Int */
//! int64_t certo_add(int64_t a, int64_t b);
//!
//! /* greet — Certo: pub fn greet(name: Text): Text */
//! const char* certo_greet(const char* name);
//!
//! #endif /* MYMODULE_H */
//! ```

use std::fmt::Write as _;

use certo_ast::decl::{Decl, FnDecl};
use certo_ast::module::Module;

use crate::ty::{ty_to_c, ret_ty_to_c, c_ident};

/// Generate a C header for all `pub fn` declarations in `module`.
///
/// `guard_name` is used as the include-guard symbol (e.g. `"MY_MODULE_H"`).
/// If empty or `None`, it is derived from the module name.
pub fn generate_header(module: &Module, guard_name: Option<&str>) -> String {
    let mod_name = module.path.segments.iter()
        .map(|s| s.node.as_str())
        .collect::<Vec<_>>()
        .join("_")
        .replace('-', "_")
        .to_uppercase();
    let guard = guard_name
        .filter(|s| !s.is_empty())
        .map(str::to_owned)
        .unwrap_or_else(|| format!("{}_H", mod_name));

    let pub_fns: Vec<&FnDecl> = module.decls.iter()
        .filter_map(|sd| if let Decl::Fn(f) = &sd.node { Some(f) } else { None })
        .filter(|f| f.is_pub)
        .collect();

    let mut out = String::new();

    // Include guard + standard headers
    writeln!(out, "/* Generated by certo-ffi — do not edit */").unwrap();
    writeln!(out, "#ifndef {guard}").unwrap();
    writeln!(out, "#define {guard}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#include <stdint.h>").unwrap();
    writeln!(out, "#include <stdbool.h>").unwrap();
    writeln!(out, "#include <stddef.h>").unwrap();
    writeln!(out).unwrap();
    out.push_str(RUNTIME_TYPEDEFS);
    writeln!(out).unwrap();

    // One extern declaration per pub fn
    for f in &pub_fns {
        let sig = c_prototype(f);
        writeln!(out, "/* {} */", certo_sig_comment(f)).unwrap();
        writeln!(out, "{};", sig).unwrap();
        writeln!(out).unwrap();
    }

    writeln!(out, "#endif /* {guard} */").unwrap();
    out
}

// ------------------------------------------------------------------ //
// Helpers
// ------------------------------------------------------------------ //

fn c_prototype(f: &FnDecl) -> String {
    let ret = ret_ty_to_c(f.ret_ty.as_ref().map(|t| &t.node));
    // `@export("name")` overrides the default `certo_<name>` symbol — matches
    // the exported wrapper codegen emits (see `emit_module.rs`'s `export_wrappers`).
    let name = match &f.export_name {
        Some(n) => c_ident(n),
        None    => format!("certo_{}", c_ident(&f.name.node)),
    };
    let params: Vec<String> = f.params.iter()
        .map(|p| format!("{} {}", ty_to_c(&p.ty.node), c_ident(&p.name.node)))
        .collect();
    let param_str = if params.is_empty() { "void".into() } else { params.join(", ") };
    format!("{ret} {name}({param_str})")
}

fn certo_sig_comment(f: &FnDecl) -> String {
    let params: Vec<String> = f.params.iter()
        .map(|p| {
            let ty = ty_expr_str(&p.ty.node);
            format!("{}: {}", p.name.node, ty)
        })
        .collect();
    let ret = f.ret_ty.as_ref().map(|t| format!(": {}", ty_expr_str(&t.node))).unwrap_or_default();
    format!("pub fn {}({}){}", f.name.node, params.join(", "), ret)
}

fn ty_expr_str(te: &certo_ast::types::TypeExpr) -> String {
    use certo_ast::types::TypeExpr;
    match te {
        TypeExpr::Named { path, args, .. } => {
            let base = path.segments.iter().map(|s| s.node.as_str()).collect::<Vec<_>>().join(".");
            if args.is_empty() {
                base
            } else {
                let a = args.iter().map(|a| ty_expr_str(&a.node)).collect::<Vec<_>>().join(", ");
                format!("{}<{}>", base, a)
            }
        }
        TypeExpr::Option { inner, .. } => format!("{}?", ty_expr_str(&inner.node)),
        TypeExpr::Tuple { elements, .. } => {
            let els: Vec<_> = elements.iter().map(|e| ty_expr_str(&e.node)).collect();
            format!("({})", els.join(", "))
        }
        TypeExpr::Fn { params, ret, .. } => {
            let ps: Vec<_> = params.iter().map(|p| ty_expr_str(&p.node)).collect();
            format!("({}) => {}", ps.join(", "), ty_expr_str(&ret.node))
        }
        TypeExpr::Record { fields, .. } => {
            let fs: Vec<_> = fields.iter().map(|f| format!("{}: {}", f.name.node, ty_expr_str(&f.ty.node))).collect();
            format!("{{ {} }}", fs.join(", "))
        }
        TypeExpr::Ptr { inner, .. } => format!("*{}", ty_expr_str(&inner.node)),
        TypeExpr::Param { name, .. } => name.node.clone(),
        TypeExpr::DecimalParam { precision, scale, .. } => format!("Decimal({}, {})", precision, scale),
    }
}

// ------------------------------------------------------------------ //
// Minimal runtime typedefs embedded in every header
// ------------------------------------------------------------------ //

const RUNTIME_TYPEDEFS: &str = "\
/* Certo runtime types */
typedef struct { int64_t value; int8_t scale; } certo_decimal_t;
typedef struct { uint8_t bytes[16]; }           certo_uuid_t;
typedef struct { bool has_value; void* value; } certo_option_t;
typedef struct { void* value; }                 certo_tuple_t;
typedef void (*certo_fn_t)(void);";

// ------------------------------------------------------------------ //
// Tests
// ------------------------------------------------------------------ //

#[cfg(test)]
mod tests {
    use super::*;
    use certo_parser::parse;

    fn module(src: &str) -> Module { parse(src).expect("parse") }

    #[test]
    fn basic_int_fn() {
        let m = module("module M\npub fn add(a: Int, b: Int): Int = a + b\n");
        let h = generate_header(&m, None);
        assert!(h.contains("int64_t certo_add(int64_t a, int64_t b);"), "missing prototype\n{}", h);
        assert!(h.contains("#ifndef M_H"), "missing guard\n{}", h);
    }

    #[test]
    fn text_fn() {
        let m = module("module M\npub fn greet(name: Text): Text = name\n");
        let h = generate_header(&m, None);
        assert!(h.contains("const char* certo_greet(const char* name);"), "wrong text mapping\n{}", h);
    }

    #[test]
    fn private_fn_excluded() {
        let m = module("module M\nfn internal(x: Int): Int = x\n");
        let h = generate_header(&m, None);
        assert!(!h.contains("certo_internal"), "private fn must not appear\n{}", h);
    }

    #[test]
    fn unit_return_is_void() {
        let m = module("module M\npub fn doThing(): Unit = ()\n");
        let h = generate_header(&m, None);
        assert!(h.contains("void certo_doThing(void);"), "Unit should map to void\n{}", h);
    }

    #[test]
    fn custom_guard() {
        let m = module("module M\npub fn add(a: Int, b: Int): Int = a + b\n");
        let h = generate_header(&m, Some("MY_CUSTOM_GUARD_H"));
        assert!(h.contains("#ifndef MY_CUSTOM_GUARD_H"), "missing custom guard\n{}", h);
    }

    #[test]
    fn no_params_uses_void() {
        let m = module("module M\npub fn now(): Int = 0\n");
        let h = generate_header(&m, None);
        assert!(h.contains("int64_t certo_now(void);"), "no-param fn should use void\n{}", h);
    }

    #[test]
    fn export_annotation_overrides_prototype_name() {
        let m = module("module M\n@export(\"my_custom_add\")\npub fn add(a: Int, b: Int): Int = a + b\n");
        let h = generate_header(&m, None);
        assert!(h.contains("int64_t my_custom_add(int64_t a, int64_t b);"), "missing custom-named prototype\n{}", h);
        assert!(!h.contains("certo_add("), "should not also emit the default-named prototype\n{}", h);
    }
}
