//! Generate typed Certo client stubs from a JSON REST API schema.
//!
//! # Schema format
//!
//! ```json
//! {
//!   "module":   "UserApi",
//!   "base_url": "https://api.example.com",
//!   "auth":     "bearer",
//!   "endpoints": [
//!     {
//!       "name":         "get_user",
//!       "method":       "GET",
//!       "path":         "/users/{id}",
//!       "path_params":  [{ "name": "id", "ty": "Int" }],
//!       "query_params": [{ "name": "active", "ty": "Bool", "optional": true }],
//!       "body":         null,
//!       "response":     "User"
//!     },
//!     {
//!       "name":         "create_user",
//!       "method":       "POST",
//!       "path":         "/users",
//!       "path_params":  [],
//!       "query_params": [],
//!       "body":         { "ty": "CreateUserRequest" },
//!       "response":     "User"
//!     }
//!   ]
//! }
//! ```
//!
//! # Generated Certo
//!
//! ```certo
//! module UserApi
//!
//! // REST client generated by certo-ffi
//! // Base URL: https://api.example.com
//! // Auth: bearer
//!
//! // GET /users/{id}
//! pub fn get_user(id: Int, active: Bool?): User [async, io] =
//!   http_get("https://api.example.com/users/" ++ id.toString(), active)
//!
//! // POST /users
//! pub fn create_user(body: CreateUserRequest): User [async, io] =
//!   http_post("https://api.example.com/users", body)
//! ```

use std::fmt::Write as _;

use serde::Deserialize;

use crate::error::FfiError;

// ------------------------------------------------------------------ //
// Schema types
// ------------------------------------------------------------------ //

#[derive(Debug, Deserialize)]
pub struct RestSchema {
    /// Certo module name for the generated client file.
    pub module:    String,
    /// Base URL prepended to all endpoint paths.
    pub base_url:  String,
    /// Authentication scheme: `"bearer"`, `"basic"`, `"api_key"`, or omit.
    pub auth:      Option<String>,
    pub endpoints: Vec<Endpoint>,
}

#[derive(Debug, Deserialize)]
pub struct Endpoint {
    /// Certo function name.
    pub name:         String,
    /// HTTP method (`"GET"`, `"POST"`, `"PUT"`, `"PATCH"`, `"DELETE"`).
    pub method:       String,
    /// URL path, with `{param}` placeholders for path parameters.
    pub path:         String,
    #[serde(default)]
    pub path_params:  Vec<Param>,
    #[serde(default)]
    pub query_params: Vec<Param>,
    /// Request body type.  `null` / absent for GET/DELETE.
    pub body:         Option<BodyDef>,
    /// Certo type returned on success.  `null` means `Unit`.
    pub response:     Option<String>,
}

#[derive(Debug, Deserialize)]
pub struct Param {
    pub name:     String,
    pub ty:       String,
    #[serde(default)]
    pub optional: bool,
}

#[derive(Debug, Deserialize)]
pub struct BodyDef {
    pub ty: String,
}

// ------------------------------------------------------------------ //
// Public API
// ------------------------------------------------------------------ //

/// Parse a REST schema from a JSON string.
pub fn parse_schema(json: &str) -> Result<RestSchema, FfiError> {
    serde_json::from_str(json).map_err(|e| FfiError::SchemaError(e.to_string()))
}

/// Generate a Certo source file (module + `pub fn` stubs) from a `RestSchema`.
pub fn generate_client(schema: &RestSchema) -> String {
    let mut out = String::new();

    writeln!(out, "module {}", schema.module).unwrap();
    writeln!(out).unwrap();
    writeln!(out, "// REST client generated by certo-ffi — do not edit").unwrap();
    writeln!(out, "// Base URL: {}", schema.base_url).unwrap();
    if let Some(auth) = &schema.auth {
        writeln!(out, "// Auth: {}", auth).unwrap();
    }

    for ep in &schema.endpoints {
        writeln!(out).unwrap();
        emit_endpoint(&mut out, ep, &schema.base_url);
    }

    out
}

// ------------------------------------------------------------------ //
// Per-endpoint codegen
// ------------------------------------------------------------------ //

fn emit_endpoint(out: &mut String, ep: &Endpoint, base_url: &str) {
    // Comment header
    writeln!(out, "// {} {}", ep.method.to_uppercase(), ep.path).unwrap();

    // Function signature
    let params = collect_fn_params(ep);
    let ret_ty = ep.response.as_deref().unwrap_or("Unit");
    let param_str = params.join(", ");
    writeln!(out, "pub fn {}({}): {} [async, io] =", ep.name, param_str, ret_ty).unwrap();

    // Body expression
    let url_expr = build_url_expr(base_url, &ep.path, &ep.path_params);
    let method   = ep.method.to_lowercase();

    let call = match method.as_str() {
        "get" | "delete" => {
            let query_args = query_args_str(&ep.query_params);
            if query_args.is_empty() {
                format!("  http_{}({})", method, url_expr)
            } else {
                format!("  http_{}({}, [{}])", method, url_expr, query_args)
            }
        }
        "post" | "put" | "patch" => {
            let body_arg = if ep.body.is_some() { "body" } else { "()" };
            format!("  http_{}({}, {})", method, url_expr, body_arg)
        }
        other => format!("  http_request(\"{}\", {})", other.to_uppercase(), url_expr),
    };

    writeln!(out, "{}", call).unwrap();
}

fn collect_fn_params(ep: &Endpoint) -> Vec<String> {
    let mut params = Vec::new();
    for p in &ep.path_params {
        params.push(format_param(p));
    }
    for p in &ep.query_params {
        params.push(format_param(p));
    }
    if let Some(body) = &ep.body {
        params.push(format!("body: {}", body.ty));
    }
    params
}

fn format_param(p: &Param) -> String {
    if p.optional {
        format!("{}: {}?", p.name, p.ty)
    } else {
        format!("{}: {}", p.name, p.ty)
    }
}

/// Build a Certo string expression for the full URL.
///
/// Path placeholders like `{id}` become `id.toString()` interpolated via `++`.
fn build_url_expr(base_url: &str, path: &str, path_params: &[Param]) -> String {
    // Remove trailing slash from base to avoid double slashes
    let base = base_url.trim_end_matches('/');

    // Split path on `{...}` segments
    let mut parts: Vec<String> = Vec::new();
    let mut rest = path;
    while let Some(open) = rest.find('{') {
        if open > 0 {
            parts.push(format!("\"{}{}\"", base_in_first(&parts, base), &rest[..open]));
        } else if parts.is_empty() {
            // First segment — attach base
            parts.push(format!("\"{}\"", base));
        }
        rest = &rest[open + 1..];
        if let Some(close) = rest.find('}') {
            let param_name = &rest[..close];
            let p = path_params.iter().find(|p| p.name == param_name);
            let conv = match p.map(|p| p.ty.as_str()) {
                Some("Int") | Some("Float") => format!("{}.toString()", param_name),
                _ => param_name.to_owned(),
            };
            parts.push(conv);
            rest = &rest[close + 1..];
        }
    }
    // Remaining literal
    if !rest.is_empty() {
        if parts.is_empty() {
            parts.push(format!("\"{}{}\"", base, rest));
        } else {
            parts.push(format!("\"{}\"", rest));
        }
    }
    if parts.is_empty() {
        format!("\"{}\"", base)
    } else {
        parts.join(" ++ ")
    }
}

fn base_in_first(parts: &[String], base: &str) -> String {
    if parts.is_empty() { base.to_owned() } else { String::new() }
}

fn query_args_str(params: &[Param]) -> String {
    params.iter()
        .map(|p| format!("(\"{}\", {})", p.name, p.name))
        .collect::<Vec<_>>()
        .join(", ")
}

// ------------------------------------------------------------------ //
// Tests
// ------------------------------------------------------------------ //

#[cfg(test)]
mod tests {
    use super::*;

    const SCHEMA: &str = r#"
    {
      "module":   "UserApi",
      "base_url": "https://api.example.com",
      "auth":     "bearer",
      "endpoints": [
        {
          "name":        "get_user",
          "method":      "GET",
          "path":        "/users/{id}",
          "path_params": [{ "name": "id", "ty": "Int" }],
          "response":    "User"
        },
        {
          "name":      "list_users",
          "method":    "GET",
          "path":      "/users",
          "query_params": [{ "name": "page", "ty": "Int", "optional": true }],
          "response":  "List<User>"
        },
        {
          "name":     "create_user",
          "method":   "POST",
          "path":     "/users",
          "body":     { "ty": "CreateUserRequest" },
          "response": "User"
        },
        {
          "name":        "delete_user",
          "method":      "DELETE",
          "path":        "/users/{id}",
          "path_params": [{ "name": "id", "ty": "Int" }],
          "response":    null
        }
      ]
    }
    "#;

    fn schema() -> RestSchema { parse_schema(SCHEMA).expect("parse") }

    #[test]
    fn parse_schema_ok() {
        let s = schema();
        assert_eq!(s.module,   "UserApi");
        assert_eq!(s.endpoints.len(), 4);
    }

    #[test]
    fn module_declaration_present() {
        let src = generate_client(&schema());
        assert!(src.starts_with("module UserApi"), "wrong module header\n{}", src);
    }

    #[test]
    fn get_fn_has_async_io() {
        let src = generate_client(&schema());
        assert!(src.contains("[async, io]"), "missing effects\n{}", src);
    }

    #[test]
    fn path_param_interpolated() {
        let src = generate_client(&schema());
        assert!(src.contains("id.toString()"), "missing path interpolation\n{}", src);
    }

    #[test]
    fn post_includes_body() {
        let src = generate_client(&schema());
        assert!(src.contains("http_post("), "missing http_post\n{}", src);
        assert!(src.contains("body: CreateUserRequest"), "missing body param\n{}", src);
    }

    #[test]
    fn delete_returns_unit() {
        let src = generate_client(&schema());
        assert!(src.contains(": Unit [async, io]"), "DELETE should return Unit\n{}", src);
    }

    #[test]
    fn optional_query_param_has_question_mark() {
        let src = generate_client(&schema());
        assert!(src.contains("page: Int?"), "optional param should have ?\n{}", src);
    }

    #[test]
    fn invalid_json_gives_schema_error() {
        let err = parse_schema("not json").unwrap_err();
        assert!(matches!(err, FfiError::SchemaError(_)));
    }

    #[test]
    fn base_url_in_generated_code() {
        let src = generate_client(&schema());
        assert!(src.contains("api.example.com"), "missing base URL\n{}", src);
    }
}
