//! Generate JavaScript / TypeScript bindings for exported Certo functions.
//!
//! Only `pub fn` declarations with supported numeric types are included in
//! the typed interface.  Functions with Text/record parameters are still
//! exported but listed as `opaque` with a prose explanation.
//!
//! # Output
//!
//! For a module with:
//!
//! ```certo
//! pub fn add(a: Int, b: Int): Int = a + b
//! pub fn greet(name: Text): Text = name
//! ```
//!
//! `generate_dts()` emits:
//!
//! ```typescript
//! export interface CertoExports {
//!   add(a: bigint, b: bigint): bigint;
//!   // greet: Text params/return require manual memory management — see docs
//! }
//! export declare function load(path: string): Promise<CertoExports>;
//! ```
//!
//! `generate_js()` emits a small ESM loader.

use certo_ast::decl::{Decl, FnDecl};
use certo_ast::module::Module;
use certo_ast::types::TypeExpr;

// ------------------------------------------------------------------ //
// Public API
// ------------------------------------------------------------------ //

/// Generate a `.d.ts` TypeScript declaration file.
pub fn generate_dts(module: &Module, module_name: &str) -> String {
    let fns = collect_pub_fns(module);
    let mut out = String::new();

    out.push_str("// Generated by certo-wasm — do not edit\n");
    out.push_str(&format!("// Module: {}\n\n", module_name));

    out.push_str("export interface CertoExports {\n");
    for f in &fns {
        match fn_ts_sig(f) {
            Some(sig) => out.push_str(&format!("  {};\n", sig)),
            None      => out.push_str(&format!(
                "  // {name}: params or return type require memory management — use raw WASM exports\n",
                name = f.name.node
            )),
        }
    }
    out.push_str("}\n\n");

    // Loader declaration
    out.push_str(
        "/**\n\
         * Load the compiled Certo WASM module.\n\
         * @param path  Path or URL to the .wasm file.\n\
         */\n\
        export declare function load(path: string | URL): Promise<CertoExports>;\n"
    );

    out
}

/// Generate an ESM JavaScript loader.
pub fn generate_js(module: &Module, module_name: &str, _wasm_filename: &str) -> String {
    let fns = collect_pub_fns(module);
    let mut out = String::new();

    out.push_str("// Generated by certo-wasm — do not edit\n");
    out.push_str(&format!("// Module: {}\n\n", module_name));

    // load() function
    out.push_str("export async function load(path) {\n");
    out.push_str("  const bytes = typeof fetch !== 'undefined'\n");
    out.push_str("    ? await fetch(path).then(r => r.arrayBuffer())\n");
    out.push_str("    : await import('fs').then(fs => fs.promises.readFile(path));\n");
    out.push_str("  const { instance } = await WebAssembly.instantiate(bytes, {\n");
    out.push_str("    wasi_snapshot_preview1: makeWasiStub(),\n");
    out.push_str("  });\n");
    out.push_str("  const exp = instance.exports;\n");
    out.push_str("  return {\n");

    for f in &fns {
        if fn_ts_sig(f).is_some() {
            let name = &f.name.node;
            let js_name = llvm_fn_name(name);
            out.push_str(&format!("    {name}: (...args) => exp.{js_name}(...args),\n",
                name    = name,
                js_name = js_name));
        }
    }

    out.push_str("  };\n}\n\n");

    // Minimal WASI stub (enough for numeric-only modules)
    out.push_str(
        "function makeWasiStub() {\n\
        \x20 // Minimal WASI stub for numeric-only modules.\n\
        \x20 // Replace with a full WASI implementation (e.g. @bjorn3/browser_wasi_shim)\n\
        \x20 // if your module uses println() or other I/O.\n\
        \x20 const noop = () => 0;\n\
        \x20 return {\n\
        \x20   fd_write: noop, fd_read: noop, fd_close: noop,\n\
        \x20   proc_exit: code => { throw new Error(`exit(${code})`); },\n\
        \x20   environ_get: noop, environ_sizes_get: noop,\n\
        \x20   args_get: noop, args_sizes_get: noop,\n\
        \x20   clock_time_get: noop, random_get: noop,\n\
        \x20 };\n\
        }\n"
    );

    out
}

/// Generate a simple HTML page that loads the WASM and calls exported functions
/// via a JS console — useful for quick browser testing.
pub fn generate_html(module_name: &str, js_filename: &str) -> String {
    format!(r#"<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>{name} — Certo WASM</title></head>
<body>
<h1>{name}</h1>
<pre id="output">Loading…</pre>
<script type="module">
import {{ load }} from './{js}';
const wasm = await load('./{name}.wasm');
document.getElementById('output').textContent =
  'Module loaded. Available exports:\n' + Object.keys(wasm).join('\n');
// Call your exports here, e.g.: wasm.add(1n, 2n)
</script>
</body>
</html>
"#, name = module_name, js = js_filename)
}

// ------------------------------------------------------------------ //
// Helpers
// ------------------------------------------------------------------ //

fn collect_pub_fns(module: &Module) -> Vec<FnDecl> {
    module.decls.iter()
        .filter_map(|sd| if let Decl::Fn(f) = &sd.node { Some(f.clone()) } else { None })
        .filter(|f| f.is_pub)
        .collect()
}

/// TypeScript type for a Certo `TypeExpr`.  Returns `None` for types that
/// require linear-memory management (Text, records, …).
fn ts_type(te: &TypeExpr) -> Option<&'static str> {
    match te {
        TypeExpr::Named { path, .. } => {
            let name = path.segments.last()?.node.as_str();
            match name {
                "Int"   => Some("bigint"),   // WASM i64
                "Float" => Some("number"),   // WASM f64
                "Bool"  => Some("boolean"),  // WASM i32 (0/1)
                _       => None,             // opaque
            }
        }
        TypeExpr::Tuple { elements, .. } if elements.is_empty() => Some("void"),
        _ => None,
    }
}

/// Full TypeScript signature for a function.  Returns `None` if any param or
/// return type is opaque.
fn fn_ts_sig(f: &FnDecl) -> Option<String> {
    let ret_ts = match &f.ret_ty {
        None     => "void",
        Some(te) => ts_type(&te.node)?,
    };
    let params: Option<Vec<String>> = f.params.iter()
        .map(|p| ts_type(&p.ty.node).map(|t| format!("{}: {}", p.name.node, t)))
        .collect();
    let params = params?;
    Some(format!("{}({}): {}", f.name.node, params.join(", "), ret_ts))
}

fn llvm_fn_name(name: &str) -> String {
    format!("certo_{}", name.replace('.', "_").replace('-', "_"))
}

// ------------------------------------------------------------------ //
// Tests
// ------------------------------------------------------------------ //

#[cfg(test)]
mod tests {
    use super::*;
    use certo_parser::parse;

    fn module(src: &str) -> Module {
        parse(src).expect("parse error")
    }

    #[test]
    fn numeric_pub_fn_appears_in_dts() {
        let m   = module("module M\npub fn add(a: Int, b: Int): Int = a + b\n");
        let dts = generate_dts(&m, "M");
        assert!(dts.contains("add(a: bigint, b: bigint): bigint"), "missing typed sig\n{}", dts);
    }

    #[test]
    fn text_fn_is_commented_out_in_dts() {
        let m   = module("module M\npub fn greet(name: Text): Text = name\n");
        let dts = generate_dts(&m, "M");
        assert!(dts.contains("// greet:"), "expected comment for Text fn\n{}", dts);
    }

    #[test]
    fn private_fn_not_in_dts() {
        let m   = module("module M\nfn internal(x: Int): Int = x\n");
        let dts = generate_dts(&m, "M");
        assert!(!dts.contains("internal("), "private fn should not appear\n{}", dts);
    }

    #[test]
    fn js_loader_contains_export() {
        let m  = module("module M\npub fn add(a: Int, b: Int): Int = a + b\n");
        let js = generate_js(&m, "M", "M.js");
        assert!(js.contains("add:"), "missing export in JS\n{}", js);
        assert!(js.contains("certo_add"), "missing wasm export name\n{}", js);
    }

    #[test]
    fn bool_fn_typed_as_boolean() {
        let m   = module("module M\npub fn pos(x: Int): Bool = x > 0\n");
        let dts = generate_dts(&m, "M");
        assert!(dts.contains("boolean"), "Bool should be boolean\n{}", dts);
    }
}
